Templates design updates
cds-snc/notification-admin pull request #1026
Opened 2021-05-12 15:44 UTC by AntoineAugusti

2021-05-14 17:54 UTC, AntoineAugusti commented on app/assets/javascripts/scheduler/SetDateTime/SetDateTime.js
Update how the scheduler is displayed. Previously it was appearing when selecting radio buttons, now you can make it appear when clicking a button. If the scheduler is shown and you click "send now", make sure we actually clear the scheduled time

2021-05-14 17:54 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header.html
> +  <div class="pt-5 pb-6">
More vertical space around GC Notify or GC Notify + service name

2021-05-19 19:57 UTC, e-pang requested changes
Thanks Antoine, the updates are looking good. 
Just this one update:
- After clicking “Send test message to yourself” the back button goes to the personalise screen instead of back to the previous “Ready to send” screen. Can you update?

2021-05-19 20:13 UTC, anikbrazeau commented on app/translations/csv/fr.csv
> +"Edit this template","Modifier le gabarit"
The heading when you click in French becomes "Modifier gabarit" ... is there a way to fix that?

2021-05-19 20:13 UTC, anikbrazeau commented on app/templates/views/send.html
> +
```suggestion
```

2021-05-19 20:13 UTC, anikbrazeau commented on app/templates/views/send.html
```suggestion
  <p class="mb-0">
    {{ _('Save your file as a') }} {% set csv_acronym = _('Comma Separated Values') %}
    {% set tsv_acr = _('Tab Separated Values') %} {% set ods_acronym = _('Open Document Spreadsheet') %}
    <acronym title="{{ csv_acronym }}">{{ _('CSV') }}</acronym>,
    <acronym title="{{ tsv_acronym }}">{{ _('TSV') }}</acronym>,
    <acronym title="{{ ods_acronym }}">{{ _('ODS') }}</acronym> {{ _('or Microsoft Excel spreadsheet') }}
  </p>

```

2021-05-19 20:20 UTC, anikbrazeau commented on app/templates/views/check/ok.html
> +    {{ _("{} recipients from {}.").format(count_of_recipients, original_file_name) }}
Also seems to be 2 missing FR strings here?
<img width="636" alt="Screen Shot 2021-05-19 at 4 15 13 PM" src="https://user-images.githubusercontent.com/38330843/118878338-72d7b100-b8bd-11eb-9eaa-0b3bb2123a59.png">

"Review before sending","Réviser avant l'envoi"
"was uploaded.", "a été téléversé"

2021-05-19 20:20 UTC, anikbrazeau commented on app/templates/views/check/ok.html
> +    {{ _("The example below previews row {} from {}.").format(preview_row, original_file_name) }}
```suggestion
    {{ _("The example below previews one recipient (row {} from {}.").format(preview_row, original_file_name) }})
```

2021-05-19 20:20 UTC, anikbrazeau commented on app/translations/csv/fr.csv
> +"The example below previews row {} from {}.","L’exemple ci-dessous ne montre que la ligne {} de {}."
```suggestion
"The example below previews one recipient (row {} from {}).","L’exemple ci-dessous ne montre qu'un destinataire (de la ligne {} de {})."
```

2021-05-19 20:20 UTC, anikbrazeau commented on app/templates/views/check/ok.html
> +    {{ _("{} recipients from {}.").format(count_of_recipients, original_file_name) }}
can this be singular for 1 recipient?

2021-05-19 20:20 UTC, anikbrazeau commented on app/translations/csv/fr.csv
> +"{} recipients from {}.","{} destinataires provenant de {}."
can this be singular for 1 recipient?

2021-05-19 20:26 UTC, anikbrazeau commented on app/templates/partials/csv-send.html
> -  {% set hint= _('Example') %} {% call(item, row_number) list_table( example,
Is there a way to translate the example in French? 
"email address" =  "adresse courriel"
"phone number" = "numéro de téléphone"
"example" = "exemple"
<img width="1023" alt="Screen Shot 2021-05-19 at 4 23 48 PM" src="https://user-images.githubusercontent.com/38330843/118879602-ec23d380-b8be-11eb-83e1-a232b64f8bad.png">

2021-05-20 12:56 UTC, AntoineAugusti commented
@e-pang @anikbrazeau Thanks for your review! Addressed your feedback. Can you check one more time that things are good? @jimleroyer will check stuff on the code side just after.

2021-05-21 13:24 UTC, e-pang approved these changes
Looks good to me now, thanks for updating Antoine!

2021-05-26 03:55 UTC, jimleroyer approved these changes
It's one of these big PR where one is tempted to blindly approve. There are  many kind of changes too which does not make this easy. I tried to catch obvious things but it looks good overall.

I left a few comments, some reflecting and others that could be addressed here or later (e.g. using sha id instead of labeled version).

There is a lot in there. This is great work and will have a good impact.

2021-05-26 03:55 UTC, jimleroyer commented on requirements-app.txt
> +git+https://github.com/cds-snc/notifier-utils.git@789b96d8e015ba7df951723ddb227c03b6d331cc#egg=notifications-utils
Do we want to use a tag here instead of the commit SHA ID?

2021-05-26 11:47 UTC, merged

2021-05-26 11:48 UTC, AntoineAugusti commented
@jimleroyer Thanks for the review!

About the scheduler, I think it's out of scope for this PR. I didn't change a lot of things compared to what we have at the moment and I don't want to start _now_ a refactor of this. I do agree that it could be cleaned up! I'll log a "technical debt" card.

For the utils dependency, I used a commit sha for a short bit on this PR only because it was not merged/tagged just yet and I wanted to be able to pull it in the review app. That was a hack while this PR was in review. I've merged/tagged utils and used a tag before merging 👍