Make the request to go live form less confusing
cds-snc/notification-admin pull request #1040
Opened 2021-05-26 22:05 UTC by smcmurtry

# Summary | Résumé

I will convert this from a draft and once the content is finalized.

Trello: https://trello.com/c/4FX6Lj1K/537-make-the-request-to-go-live-form-less-confusing
Demo: https://www.youtube.com/watch?v=AvCMQOAx9zA
Screenshot: <img width="1088" alt="Screen Shot 2021-05-26 at 4 03 31 PM" src="https://user-images.githubusercontent.com/5498428/119737055-ee94a900-be3b-11eb-9188-c202bac8f6e8.png">

# Test instructions | Instructions pour tester la modification

Steps:
- Create a new service
- click the "request to go live" link
- observe there is now a submit button on the "request to go live" page
- click the submit button, and verify that the bullets in the error message match up to the incomplete steps on the checklist
- complete the checklist, verify that the submit button now allows you to submit the request

2021-05-26 22:08 UTC, smcmurtry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make the request to go live form less confusing](https://trello.com/c/4FX6Lj1K/537-make-the-request-to-go-live-form-less-confusing)

2021-05-27 14:14 UTC, AntoineAugusti commented on app/templates/views/service-settings/request-to-go-live.html
> +        <div class="mb-12 clear-both contain-floats">
Think `clear-both contain-floats` are not needed

2021-05-27 14:14 UTC, AntoineAugusti commented on app/templates/views/service-settings/request-to-go-live.html
> +            <p class="font-bold">{{ _("Complete all the steps before submitting the request to go live:") }}</p>
If I remember correctly, banners are already bold. We may have a `banner-title` class

2021-05-27 14:14 UTC, AntoineAugusti commented on app/templates/views/service-settings/request-to-go-live.html
> +            <ul class="list-bullet">
Think it would be good to avoid duplicate checklist tasks, could you consider having a list of dict with has it been done/description/url and loop over this in the table and for errors?

2021-05-27 16:50 UTC, smcmurtry commented on app/templates/views/service-settings/request-to-go-live.html
> +        <div class="mb-12 clear-both contain-floats">
you are right!

2021-05-27 17:12 UTC, smcmurtry commented on app/templates/views/service-settings/request-to-go-live.html
> +            <p class="font-bold">{{ _("Complete all the steps before submitting the request to go live:") }}</p>
Without that class it is not bold but the `<li>` elements are: 
<img width="986" alt="Screen Shot 2021-05-27 at 11 07 26 AM" src="https://user-images.githubusercontent.com/5498428/119868233-058ad800-bedc-11eb-92e2-68737aa141a2.png">

If I use `<h2 class="banner-title">` it looks like this: 
<img width="992" alt="Screen Shot 2021-05-27 at 11 08 21 AM" src="https://user-images.githubusercontent.com/5498428/119868244-091e5f00-bedc-11eb-8f77-129f655627ac.png">

But the way the content is written, it is not exactly a title. Arguably the error message should have a title. But I think it is okay without one since this will be autofocused by screen readers when the error occurs so it will be hard to miss.

2021-05-27 17:56 UTC, smcmurtry commented on app/templates/views/service-settings/request-to-go-live.html
> +            <ul class="list-bullet">
Good idea!

2021-05-27 18:43 UTC, AntoineAugusti requested changes

2021-05-27 18:43 UTC, AntoineAugusti commented on tests/app/main/views/test_service_settings.py
> +def test_should_always_show_go_live_button(
Could you write an additional test to make sure the banner is shown when at least something has not been completed?

2021-05-27 18:43 UTC, AntoineAugusti commented on app/templates/views/service-settings/request-to-go-live.html
> +        {% for item in current_service.go_live_checklist %}
💅

2021-05-27 18:43 UTC, AntoineAugusti commented on app/models/service.py
>      def go_live_checklist_completed(self):
Could you use `go_live_checklist` here?

```py
def go_live_checklist_completed(self):
    return all([checklist['completed'] for checklist in self.go_live_checklist])

```

2021-05-27 19:14 UTC, smcmurtry commented on tests/app/main/views/test_service_settings.py
> +def test_should_always_show_go_live_button(
Will do!

2021-05-27 21:56 UTC, smcmurtry commented on app/models/service.py
>      def go_live_checklist_completed(self):
So I tried doing this, but then it broke this test: https://github.com/cds-snc/notification-admin/blob/5a53697585769a5d46b55ddc92687c326794f02f/tests/app/models/test_service.py#L289
Because the response context is now needed to get the translated text, and that test doesn't have it. I wasn't sure how to fix that test so I just reverted this change.

2021-05-27 22:04 UTC, smcmurtry commented on tests/app/main/views/test_service_settings.py
> +    client_request: ClientRequest,
Setting the type so that type hints work.

Before:
![Screen Shot 2021-05-27 at 4 03 48 PM](https://user-images.githubusercontent.com/5498428/119902925-23206780-bf05-11eb-8c59-540c6e890ee3.png)


After:
![Screen Shot 2021-05-27 at 4 03 03 PM](https://user-images.githubusercontent.com/5498428/119902849-08e68980-bf05-11eb-971a-ccfdce001af0.png)

2021-05-27 22:05 UTC, smcmurtry commented on tests/conftest.py
> +class ClientRequest:
I moved this class outside of its wrapper function so that it can be imported in the tests and used for static typing.  See my comment in the test file.

2021-05-28 13:07 UTC, AntoineAugusti commented
@smcmurtry Made a refactor commit to use the checklist in `go_live_checklist_completed`.

Actually there was a bug because the checklist used `has_team_members_status` and the other method `has_team_members`. The task list needs a status because an item (inviting people can be "in progress") https://github.com/cds-snc/notification-admin/blob/3d7bcebf968dd078ca0f7977e38217511c879bce/app/templates/components/task-list.html#L4 so we need to distinguish between booleans and "in progress".

Tried to use a lazy translation (`_l("foo"` instead of `_("foo")`) but had to use a test request context as you described.

2021-05-28 13:08 UTC, AntoineAugusti approved these changes
Really good!

Thanks for going the extra kilometer and refactoring things around the checklist or the `ClientRequest`!

2021-05-28 15:07 UTC, merged