Experiment: Formatting all python files with black
cds-snc/notification-admin pull request #1049
Opened 2021-06-01 22:39 UTC by smcmurtry

# Summary | Résumé

## What is this?!

As an experiment, I used the python formatter [Black](https://github.com/psf/black#the-uncompromising-code-formatter) to automatically format all the python files in our codebase.

## Why?!

I have always found it tedious to fix my formatting errors by hand. Our test suite tells us which lines in which files need fixing, but it is still a manual task to understand each error and then go and fix it. This adds to the long list of things that slows me down when I work on Notify. To quote the sales pitch from Black:
> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

## Downsides

- Would make submitting code upstream, or pulling GDS code downstream more challenging
- Maybe you don't like the Black code style?

## Next steps

Some discussion! If we were to go this route, Black would need to replace the `flake8 .` code style check, since it seems flake8 wants a different code style.

2021-06-01 22:51 UTC, jimleroyer commented
+1 for cleaner code. I like the idea of having a consistent code base and that would improve it. Practically speaking though, as noted, this could make import of code harder from other forks. How frequently does that happen though? A solution could be to also format their code base with the formatter into new forks to make it easier to import too if it was such a pain (or convince them to apply black or other?).

In terms of actual formatting rules, I don't mind much personally, as long as we stick to one and it is applied on the code base.

2021-06-02 15:48 UTC, smcmurtry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automatic code formatting](https://trello.com/c/jUapnOBo/548-automatic-code-formatting)

2021-06-03 14:23 UTC, AntoineAugusti requested changes
Looks good!

Could you update the `run_tests.sh` to run `black --check` to make sure tests fail if formatting is off?

2021-06-03 14:23 UTC, AntoineAugusti commented on .flake8
>  max-line-length = 130
```suggestion
max-line-length = 88
```
To be consistent with `black`

2021-06-03 14:23 UTC, AntoineAugusti commented on Makefile
> +	black ./
Could you add `black` in `requirements-test.txt`?

2021-06-03 14:23 UTC, AntoineAugusti commented on .flake8
>  [flake8]
Do we need to update our configuration with `isort`?

https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html?highlight=isort

I feel like https://github.com/cds-snc/notification-admin/blob/master/setup.cfg may need to be updated

2021-06-03 14:23 UTC, AntoineAugusti commented on Makefile
> +	black ./
Does this format only `app` and `tests` not `venv`?

2021-06-03 14:32 UTC, smcmurtry commented on .flake8
>  [flake8]
Good catch! I'll do that.

2021-06-03 14:33 UTC, smcmurtry commented on Makefile
> +	black ./
Black is in [`requirements_for_test.txt`](https://github.com/cds-snc/notification-admin/blob/experiment/adding-black/requirements_for_test.txt#L16)

2021-06-03 14:34 UTC, smcmurtry commented on Makefile
> +	black ./
> Does this format only `app` and `tests` not `venv`?

Good call, I'll change this to `black ./app ./tests`

2021-06-03 14:37 UTC, smcmurtry commented on .flake8
>  max-line-length = 130
I set the black line length to be 130 over here: https://github.com/cds-snc/notification-admin/blob/experiment/adding-black/pyproject.toml#L2. 

But I can change them both to be 88 if you prefer.

2021-06-03 14:38 UTC, AntoineAugusti commented on .flake8
>  max-line-length = 130
Sounds good, sorry I missed this, many files were changed 😅

2021-06-03 14:41 UTC, smcmurtry commented
> Could you update the `run_tests.sh` to run `black --check` to make sure tests fail if formatting is off?

Yes! Good idea.

2021-06-03 14:44 UTC, smcmurtry commented on .flake8
>  max-line-length = 130
Haha, yes this file was buried in the 182 other files that were changed.

2021-06-03 15:16 UTC, AntoineAugusti approved these changes

2021-06-03 15:20 UTC, merged