Aria menu bar
cds-snc/notification-admin pull request #1200
Opened 2021-11-18 14:05 UTC by amazingphilippe

# Summary | Résumé

Fixes https://github.com/cds-snc/notification-planning/issues/75

This PR adds in better keyboard support for the account menubutton.

In a nutshell, it allows to use the up and down arrows to interact with the menu. 

It also fixes the missing closing mechanisms: 
1. When a user clicks outside of the menu
2. Pressing esc works from anywhere, not just within the menu. 

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

# Help requested | Aide requise

- [ ] We probably want to add tests to make sure we don't break it in the future.
- [ ] There is an issue with voiceover that I'm not sure we are causing. Menu items are read twice and simultaneously. Could be a VO bug too..

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux
      langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce
      que ça devrait être divisé en de plus petites demandes de tirage (« pull
      requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2021-11-23 14:34 UTC, amazingphilippe commented
This works as expected by ARIA, but I have fortunately stumbled upon vast amounts of critique of this behavior. Menu buttons and menubars strictly are meant for application like behaviour. What we have is not a menubutton, but a simple navigation that can be toggled. 

Sources

https://adrianroselli.com/2017/10/dont-use-aria-menu-roles-for-site-nav.html
https://adrianroselli.com/2019/06/link-disclosure-widget-navigation.html
https://marcus.io/blog/menu-or-not

In this last revision, I pulled out the menu and menuitem roles and toned down the keymapping back to what it was before. 
I did revise the markup to wrap the whole thing in a nav, and wrap the links in a unordered list.

I followed this example from inclusive components. https://inclusive-components.design/menus-menu-buttons/

2021-11-23 18:38 UTC, jimleroyer requested changes
**Breaking bug**

The mouse click on the menu is broken when in desktop view.

**Potential improvements** (issue also present in production env): 

Pressing the `escape` button once the menu is expanded should collapse the menu on desktop view. This works fine in mobile view it seems.

2021-11-23 18:38 UTC, jimleroyer commented on app/assets/javascripts/menu.js
> +      let flag = false;
Do we really need this flag? It seems it occurs in only one case.

2021-11-23 18:38 UTC, jimleroyer commented on app/assets/javascripts/menu.js
> +      }
This could be a utility function if we reuse it elsewhere as in [line 109](https://github.com/cds-snc/notification-admin/pull/1200/files#diff-7aac0d62bb9e3d7b5f83f420cacda92dd22201248e8e29b4303512c7b3cec254R109).

2021-11-23 18:38 UTC, jimleroyer commented on app/templates/partials/nav/account_menu.html
> +<nav class="hidden md:visible md:flex relative justify-end inline-block text-left w-full text-blue visited:text-blue
Cool to use `nav` instead.

2021-11-23 18:38 UTC, jimleroyer commented on app/templates/partials/nav/account_menu.html
> +  <ul
Is it better to use a list for the menu items?

2021-11-23 18:38 UTC, jimleroyer commented on app/assets/javascripts/menu.js
> +      this.hasFocus = true;
This is great to track this so behavior is improved. 👍

2021-11-23 18:41 UTC, amazingphilippe commented
> The mouse click on the menu is broken when in desktop view.

Oof missed this one!

2021-11-26 16:30 UTC, amazingphilippe commented on app/templates/partials/nav/account_menu.html
> +  <ul
If the CSS styles are disabled, lists are a good way to leverage HTML to organize the content of the page. Otherwise this has no impact on anything else!

2021-11-26 18:16 UTC, amazingphilippe commented on app/assets/javascripts/menu.js
> +      let flag = false;
Maybe you can help me on this one. Is there a difference if this code is executed within the switch, or after? I'm not sure I'll be able to see the difference.

2021-11-29 22:59 UTC, jimleroyer commented on app/assets/javascripts/menu.js
> +      let flag = false;
I don't think there will be any difference if you'd put the flag code within the switch. Moving the code inline and with a function call would make it more readable though IMO.

2021-11-29 23:07 UTC, jimleroyer commented
Potential improvements: Pressing the escape button once the menu is expanded should collapse the menu on mobile view when no tab happened yet.

The switch code can be simplified as well with the usage of the flag which unnecessarily moves the logic outside of its contextual scope.

I will approve the PR though as this really improves the functionality of the menu overall. Phil and I can talk about next steps if he'd prefer to deal with these in another PR or now.

2021-11-29 23:08 UTC, jimleroyer approved these changes
Thanks for improving the functionality around this, especially to detect if it has current focus or not. 👍

2021-11-30 14:53 UTC, amazingphilippe commented
> The switch code can be simplified as well with the usage of the flag which unnecessarily moves the logic outside of its contextual scope.

Further work also revealed that the switch case isn't needed as space and enter are the default key mapping for a button element.

2021-11-30 16:45 UTC, merged