Add template preview button
cds-snc/notification-admin pull request #1241
Opened 2022-03-07 19:57 UTC by sastels

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2022-03-10 13:45 UTC, amazingphilippe commented
I think I found a flaw in our logic:

1. Let's say I edit a template, preview it, then decide I don't want to change anything. So I go back and navigate somewhere else. 
2. The template is still saved, even if I didn't press on the save button.

Similar when creating a template:
1. I start writing my template, preview it, and decide not to save it. 
2. I'll have a surprise when I see my template in the template folder!

2022-03-10 14:21 UTC, sastels commented
This is true. I don't think there's an easy way around this currently. Though we might be able to save some data temporarily in the session... I've done that before. Let me take a look at that...

2022-03-22 13:41 UTC, amazingphilippe commented on app/templates/views/templates/preview_template.html
> +        template._template.name,
Looking through the a11y audit, we have some issues about descriptive headings. I'm wondering if we could use this here and have the heading say `"Previewing template {template.name}"` or in French `"Aperçu du gabarit {template.name}"`

2022-03-22 19:20 UTC, sastels commented on app/templates/views/templates/preview_template.html
> +        template._template.name,
Done. Wondering if the template name should be in quotes?
![image](https://user-images.githubusercontent.com/8228248/159558859-71f15565-1431-4b45-a4a8-0f697fb2ee39.png)

2022-03-24 19:43 UTC, amazingphilippe commented on app/templates/views/templates/preview_template.html
> +        template._template.name,
I think this is okay. Its consistent with How I did headings in the template folders. We can revisit in bulk when we find out what is best!

2022-03-25 16:10 UTC, jimleroyer reviewed
Would there be UI tests we can add if we added a new screen? (I can't see the actual changes on the deployed instances at the moment, as I have some trouble with authenticating in staging atm).

2022-03-25 16:15 UTC, sastels commented on app.json
> +      "plan": "heroku-redis:hobby-dev"
This adds redis to heroku review apps so that the preview screen will work on them 😅

2022-03-25 16:18 UTC, sastels commented on app/main/views/templates.py
> +            redis_client.set(key=f"{prefix}-{key}", value=value.encode(), ex=int(timedelta(days=1).total_seconds()))
Yes, I'm storing them in redis here - the flask `session` is limited to 4K in size, while we (prod services) have several templates greater than 10K in size.

2022-03-25 16:18 UTC, sastels commented on app/main/views/templates.py
> +        redis_client.delete(f"{prefix}-{key}")
That would be useful 👍

2022-03-25 16:21 UTC, sastels commented on app/main/views/templates.py
> +        if template_id and service_id
yeah, I agree looking at it that it's hard to follow. Likely clearer to just compute it outside the `get_template()` function.

2022-03-25 17:23 UTC, amazingphilippe commented
> Would there be UI tests we can add if we added a new screen? (I can't see the actual changes on the deployed instances at the moment, as I have some trouble with authenticating in staging atm).

Good question, I'm wondering if we could borrow some tests from the template page and do some checks for rendering proper html. The preview page is essentially the same as the template page, minus all the distractions.

2022-03-30 15:33 UTC, amazingphilippe requested changes
Just one or two things to change for a11y:
- [x] Prepend the page heading to the page title on the preview page
- [ ] Maybe this would be extra: We should have a lang attribute on the email preview, and everywhere we preview a message. If too extra, we should create another issue for this.

2022-04-05 17:14 UTC, sastels commented on app/main/views/templates.py
> +preview_data_keys = [
refactored the code to not need that constant

2022-04-05 18:53 UTC, jimleroyer commented
I thought in the beginning we'd use caching on the client side for some specific reason but my assumptions probably were wrong. Why do we cache the template preview in the end? Asking to clear out my confusion around this.

2022-04-05 19:12 UTC, sastels commented
> I thought in the beginning we'd use caching on the client side for some specific reason but my assumptions probably were wrong. Why do we cache the template preview in the end? Asking to clear out my confusion around this.

- caching it so we can go to the preview page without saving the template in the database.
- I looked at adding the template to the client side `session` cache but there's a 4K limit on how big that can be.

2022-04-05 20:02 UTC, sastels commented
Added more tests around the new preview page. Note that rendering the template is done by ` notifications_utils` code and is tested there. Here I've added tests for the stuff around the template.

2022-04-05 20:03 UTC, sastels commented
> * Maybe this would be extra: We should have a lang attribute on the email preview, and everywhere we preview a message. If too extra, we should create another issue for this.

As discussed IRL we'll create a new issue to investigate this (basically: what lang tag should we use?)

2022-04-05 20:08 UTC, sastels commented on app/main/views/templates.py
> +        redis_client.delete(f"{prefix}-{key}")
I looked into this a little and I think they don't really apply / would make the code more confusing to try to shoe-horn them in. For example, the `@cache.set` decorator returns the cached value, and if it's not there calls the function and then sets the cache value. In this PR, in one spot we want to set the key regardless if it already exists, and in another spot we want to get the value of the key (and if it's not set it's an error).

I did steal some code from `cache` though, that simplified things substantially - instead of setting the keys individually, I now just take the data dict, json it, and set one key to the json string.

2022-04-05 20:42 UTC, jimleroyer approved these changes
LGTM -- if everything is fine with @amazingphilippe requests

2022-04-06 12:45 UTC, amazingphilippe approved these changes
👍

2022-04-06 13:46 UTC, merged