Fix/login event
cds-snc/notification-admin pull request #1267
Opened 2022-04-19 19:23 UTC by andrewleith

# Summary | Résumé

Create a LoginEvent when a user is forced to update their password, or requests a password reset, as this process automatically logs the user in. The user will see this even on the Sign-in History page when they log in.

# Test instructions | Instructions pour tester la modification

See cds-snc/notification-planning#615 for more details including test plan.

2022-04-20 19:03 UTC, jzbahrai reviewed
looks good to me but will also want a second review.

2022-04-20 19:55 UTC, jzbahrai approved these changes

2022-04-21 13:56 UTC, sastels requested changes
Code looks good with one minor request. Haven't tested it yet, will do that ASAP.

2022-04-21 13:56 UTC, sastels commented on app/main/views/authenticator.py
> +            self.user.update_password(session["user_details"]["password"], session["user_details"]["loginData"])
Should also check if `loginData` is a key in `session.get("user_details", {})`

2022-04-21 14:23 UTC, andrewleith commented on app/main/views/authenticator.py
> +            self.user.update_password(session["user_details"]["password"], session["user_details"]["loginData"])
Done.

2022-04-21 16:19 UTC, sastels approved these changes
Tested locally, verified that login_events table is getting new rows for forced password reset. Good job!

2022-04-21 17:40 UTC, merged

2022-04-21 18:00 UTC, jimleroyer reviewed
Great job @andrewleith ! 👏