A11y/sending email
cds-snc/notification-admin pull request #1273
Opened 2022-04-29 12:13 UTC by andrewleith

# Summary | Résumé

Improve the UX of the add-service flow by automatically suggesting fixes to the sending email name.  
The page will now:
- warn the user when they enter invalid characters
- attempt to automatically fix them
- allow the user to review and/or edit before continuing

# Test instructions | Instructions pour tester la modification
## scenario 1 - invalid characters
- Navigate to `/add-service`
- Enter a **service name**
- Enter an invalid **sending email address name**: `Canadian Digital Service - Service Numerique Canadién`
- Click **Continue**
- Ensure it gets fixed to: `canadian.digital.service-service.numerique.canadien`
- Ensure you can continue to the next screen in the wizard

## scenario 2 - valid characters
- Navigate to `/add-service`
- Enter a **service name**
- Enter a valid **sending email address name**: `canadian.digital.service-service.numerique.canadien``
- Click **Continue**
- Ensure you can continue to the next screen in the wizard without any warning

fixes cds-snc/notification-planning#478

2022-04-29 15:11 UTC, amazingphilippe requested changes
Just left the content changes inline. I just want to re-review once the right content is in, and do some a11y scanning and voiceover testing

2022-04-29 15:11 UTC, amazingphilippe commented on app/templates/partials/add-service/step-choose-email.html
> +<p>{{ _('Only enter the name before the at symbol using lowercase letters, periods, dashes or underscores.') }}</p>
Content change 1: `"You may use letters, numbers, dots, dashes or underscores.","Vous pouvez utiliser des lettres, des chiffres, des points, des tirets ou des barres de soulignement."`

2022-04-29 15:11 UTC, amazingphilippe commented on app/templates/partials/add-service/step-choose-email.html
> +    {% set hint_txt = _('Up to 64 characters. Only enter the name before the at symbol, without spaces.') %}
Content change 2: `"Up to 64 characters. Enter what comes before the at symbol, without spaces.","Jusqu'à 64 caractères. Entrez ce qui précède le a commercial, sans espaces."`

2022-04-29 15:11 UTC, amazingphilippe commented on app/main/validators.py
>          raise ValidationError(_l("This entry must contain valid characters for an email address."))
Content change 3: `"Make sure we formatted your email address correctly.","Assurez-vous que le formatage automatique de votre adresse vous convient."`

2022-05-02 13:52 UTC, amazingphilippe reviewed
Found an issue with the page layout. Other than that looks good to me!

2022-05-02 13:52 UTC, amazingphilippe commented on app/templates/views/add-service.html
> +  <div class="float-left py-0 px-0 px-gutterHalf box-border">
We need to add the `w-full` to replace `md:w-2/3` class here to make sure the content doesn't go beyond 100% of the page width. 

Otherwise we can get horizontal scrolling: 
<img width="1314" alt="Capture d’écran, le 2022-05-02 à 09 07 27" src="https://user-images.githubusercontent.com/5230720/166239111-2882408b-c7d0-4032-affd-182e1c273e77.png">

2022-05-02 17:56 UTC, andrewleith commented on app/templates/views/add-service.html
> +  <div class="float-left py-0 px-0 px-gutterHalf box-border">
Good catch, thanks.  I just pushed the fix for this.

2022-05-02 18:27 UTC, amazingphilippe approved these changes
🎉

2022-05-03 13:32 UTC, merged