Task/fix dict list error
cds-snc/notification-admin pull request #1308
Opened 2022-08-02 16:19 UTC by jzbahrai

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2022-08-15 16:04 UTC, sastels commented on app/main/forms.py
> +#     )
🔥

2022-08-15 16:08 UTC, sastels commented on app/main/views/add_service.py
> +    current_step_is_junk = ""
This is just boolean later I thing? If so should just be `False` here

2022-08-15 16:09 UTC, sastels commented on app/main/views/add_service.py
> +        current_step_is_junk = True if (current_step is not None and current_step not in WIZARD_ORDER) else False
could just say 
```
current_step_is_junk = current_step is not None and current_step not in WIZARD_ORDER
```

2022-08-15 16:18 UTC, sastels submitted a review, later dismissed
Code LGTM, just a few small things.

A bit odd that we have a different design for setting the initial email vs the "Change your sending email address" page perhaps? Maybe something to look at in the future.

2022-08-15 18:14 UTC, jzbahrai commented on app/main/views/add_service.py
> +        current_step_is_junk = True if (current_step is not None and current_step not in WIZARD_ORDER) else False
done

2022-08-15 18:14 UTC, jzbahrai commented on app/main/views/add_service.py
> +    current_step_is_junk = ""
done

2022-08-15 18:15 UTC, jzbahrai commented
@amazingphilippe given @sastels comment is that a change we need to do as well? maybe not attacked to this PR but just in general

2022-08-15 19:58 UTC, amazingphilippe commented
> is that a change we need to do as well? maybe not attacked to this PR but just in general

Yeah, lets make this a new story and tackle it later!

2022-08-15 20:06 UTC, amazingphilippe commented
Found a few things:
1. We need some emphasis on the highlighted parts here. Either have a background colour or bolding the text. <img width="477" alt="Capture d’écran, le 2022-08-15 à 15 00 09" src="https://user-images.githubusercontent.com/5230720/184708589-3dd2f7c0-7019-4398-a8da-e61a5b75c822.png">
2. There is a translation bug with the email address label and paragraph above. <img width="1014" alt="Capture d’écran, le 2022-08-15 à 15 57 56" src="https://user-images.githubusercontent.com/5230720/184708697-968aba41-1c3d-47d1-bfed-54fcbe0577a9.png">
4. The review app returns a 429 response sometimes, so the live preview doesn't always work. Not sure if that's a problem coming from this PR...
5. The "Create service" button isn't translated

2022-08-16 13:42 UTC, amazingphilippe requested changes
I marked where I think the translations bugs are happening.

2022-08-16 13:42 UTC, amazingphilippe commented on app/translations/csv/fr.csv
> +"Enter the part before ‘@notification.canada.ca’","L’adresse courriel se termine toujours par « @notification.canada.ca »."
These are the missing keys and translations for the input I think.
``` csv
"The email address always ends with ‘@notification.canada.ca’.","L’adresse courriel se termine toujours par « @notification.canada.ca »."
"Enter the part before ‘@notification.canada.ca’","Saisissez la partie précédant « @notification.canada.ca »."
```

2022-08-16 13:42 UTC, amazingphilippe commented on app/templates/partials/add-service/step-create-service.html
> +  {% set button_txt = _('Create Service') %}
Changing to "Create service" Without the capital S should resolve this translation bug!

2022-08-17 16:02 UTC, jzbahrai commented on app/templates/partials/add-service/step-create-service.html
> +  {% set button_txt = _('Create Service') %}
done!

2022-08-17 16:02 UTC, jzbahrai commented on app/translations/csv/fr.csv
> +"Enter the part before ‘@notification.canada.ca’","L’adresse courriel se termine toujours par « @notification.canada.ca »."
done!

2022-08-17 16:03 UTC, jzbahrai commented
@amazingphilippe made the changes other than the 429 - I am not getting that locally.

2022-08-17 17:18 UTC, amazingphilippe commented on app/assets/javascripts/url-typer.js
> +(function ($) {
Should we load this as a Module? So that we can apply the script just when we need it?

2022-08-17 17:33 UTC, amazingphilippe requested changes
A few changes after testing with voiceover locally. And I found another missing translation! Other changes look good! 👍

2022-08-17 17:33 UTC, amazingphilippe commented on app/templates/partials/add-service/step-create-service.html
> +    <p>{{ _("In this example, a government service has chosen the name ‘Renew your license’ and the email address 'renew@notification.canada.ca':") }}</p>
Just spotted that the single quotes are different than in the csv. These have the correct quotes. (I think we also need to change some single quotes in the csv. I commented later!)
`In this example, a government service has chosen the name ‘Renew your license’ and the email address ‘renew@notification.canada.ca’:`

2022-08-17 17:33 UTC, amazingphilippe commented on app/translations/csv/fr.csv
> +"In this example, a government service has chosen the name 'Renew your license' and the email address 'renew@notification.canada.ca':","Dans cet exemple, un service gouvernemental a choisi le nom « R
With the correct single quotes in English:

`In this example, a government service has chosen the name ‘Renew your license’ and the email address ‘renew@notification.canada.ca’:`

2022-08-17 17:33 UTC, amazingphilippe commented on app/templates/partials/add-service/step-create-service.html
> +        {{ _("Your service’s email address will be") }}
I found that Voiceover will read this sentence better if we add a colon before the address. Like this:

`"Your service’s email address will be:"` and then the dynamic part.

2022-08-17 17:33 UTC, amazingphilippe commented on app/templates/partials/add-service/step-create-service.html
> +        {{ _("Your service’s email address will be") }}
Same change in fr. Here is the string with the correct typographic space:
`L’adresse courriel de votre service sera :`

2022-08-17 18:09 UTC, jzbahrai commented on app/templates/partials/add-service/step-create-service.html
> +        {{ _("Your service’s email address will be") }}
done!

2022-08-17 18:09 UTC, jzbahrai commented on app/translations/csv/fr.csv
> +"In this example, a government service has chosen the name 'Renew your license' and the email address 'renew@notification.canada.ca':","Dans cet exemple, un service gouvernemental a choisi le nom « R
done!

2022-08-17 18:09 UTC, jzbahrai commented on app/templates/partials/add-service/step-create-service.html
> +    <p>{{ _("In this example, a government service has chosen the name ‘Renew your license’ and the email address 'renew@notification.canada.ca':") }}</p>
done!

2022-08-17 19:33 UTC, jzbahrai commented on app/assets/javascripts/url-typer.js
> +(function ($) {
done

2022-08-18 20:16 UTC, amazingphilippe approved these changes
lgtm!

2022-08-19 13:46 UTC, merged