remove fake tabs, use navs
cds-snc/notification-admin pull request #1332
Opened 2022-09-14 17:56 UTC by amazingphilippe

# Summary | Résumé

This updates our pill component to feel just like a nav to screen reader users. The pill component already worked like a nav, so the markup doesn't really changes. I did simplify the component a bit, especially for the label and did some CSS tweaks that should be unoticeable. 

(Fixes) https://github.com/cds-snc/notification-planning/issues/498

# Test instructions | Instructions pour tester la modification

These are the endpoints you can use to view the different pill component instances

- /monthly
- /notifications/email?status=delivered
- /templates/email

1. Check that the nav is labelled with aria-label, in both languages
2. Check that the links work, and land you where you expect

A11y QA:
- [ ] Scan with ARC toolkit or Axe devtools. For issues related to the pill
- [ ] Test the pill with voiceover on Safari
- [ ] Test the landmark menu with voiceover on Safari

2022-09-16 19:15 UTC, smcmurtry requested changes
This is great @amazingphilippe! I like the way the `<nav>` is working, it seems much clearer using voiceover:

Current prod: https://youtu.be/-rie7OE7ne4
Your review app: https://youtu.be/nygf3HhpcLY

The only thing I noticed is an issue with the focus styles - can you take a look at that before merging?

2022-09-16 19:15 UTC, smcmurtry commented on app/assets/stylesheets/tailwind/components/pill.css
> +    @apply bg-yellow text-blue;
This is causing somewhat weird behaviour where only the background of the selected link of the pill turns blue when you hover, so now the hover styles are inconsistent. Before, all links in the pill turned blue background on hover. The links already have an underline that appears on hover, so maybe we can just remove the background colour hover style?

Here's a demo - 1st our current app then your review app: https://youtu.be/XK3egR4w1Vw

2022-09-16 19:15 UTC, smcmurtry commented on app/templates/components/pill.html
> +  <nav class='pill flex' aria-label="{{ label }}">
Nice!

2022-09-16 19:38 UTC, jimleroyer commented on app/templates/components/pill.html
> +  label=""
Interesting, looks simpler now in the implementation. 👍

2022-09-16 19:51 UTC, amazingphilippe commented on app/assets/stylesheets/tailwind/components/pill.css
> +    @apply bg-yellow text-blue;
Oh yeah, that is weird. I wanted to simplify this CSS a bit. Good catch!

2022-09-20 17:41 UTC, amazingphilippe commented on app/assets/stylesheets/tailwind/components/pill.css
> +    @apply bg-yellow text-blue;
Should be fixed! I reviewed CSS specificity, and found out about LVHA ordering. added a comment for future reference.

2022-09-21 20:54 UTC, smcmurtry approved these changes
Looks good to me!

2022-09-22 17:48 UTC, merged