Adding SMS message parts to the "Review before sending" pages
cds-snc/notification-admin pull request #1334
Opened 2022-09-15 19:55 UTC by smcmurtry

# Summary | Résumé

Adding SMS message parts to the "Review before sending" pages.

We know that the SMS message parts are referred to as `billable_units`: https://github.com/cds-snc/notification-api/blob/main/app/delivery/send_to_providers.py#L98

And that is available through the `fragment_count` property on `template` objects. 

# Test instructions | Instructions pour tester la modification

TBD

2022-09-22 17:26 UTC, jzbahrai approved these changes
lgtm.

2022-09-22 17:36 UTC, sastels commented on app/main/views/send.py
> +    remaining_sms_messages = current_service.message_limit - sum(stat["requested"] for stat in statistics.values())
ah, it should be `sms_daily_limit` but I didn't add it to admin yet 😞 I can make a little admin PR that adds that...

2022-09-22 17:40 UTC, sastels requested changes
just change that `current_service.message_limit` to `current_service.sms_daily_limit` and we should be GTG!

2022-09-26 13:25 UTC, sastels approved these changes

2022-09-26 13:26 UTC, sastels commented
Looks sharp! only question: should we hide this behind the feature flag?

2022-09-26 15:57 UTC, merged