Feat/sms parts dashboard
cds-snc/notification-admin pull request #1340
Opened 2022-09-27 20:34 UTC by smcmurtry

# Summary | Résumé

Adding the "Daily Usage" section to the dashboard.

2022-09-28 21:21 UTC, andrewleith commented on app/templates/components/message-count-label.html
> +  {%- elif template_type == 'sms-parts' -%}
I noticed on the dashboard we now say "fragments" but we said "parts" on the review screens, we'll need to be consistent.

2022-09-28 21:21 UTC, andrewleith commented on app/templates/components/message-count-label.html
> +        {{ _('text message fragment') }}
🔬 Interesting that "0 items" in french is not pluralized! :til:

2022-09-28 21:21 UTC, andrewleith commented on app/templates/views/dashboard/dashboard.html
> +      <h2 class="heading-medium mt-8">
Perhaps a test to ensure this section is included when the FF is on?

2022-09-29 17:45 UTC, amazingphilippe requested changes
A few changes I would like to see in this PR:
1. If we are now counting notifications instead of fragments, we could adjust the content for this PR. Switch it later in the next dashboard PR.
2. I want the French to be at least OK in this PR, even if we have to follow it up with changes. I'll have a look at th message-count-label file and suggest changes!

2022-09-29 18:21 UTC, amazingphilippe commented
I just added the French content to this PR. But I have a problem where the plural form doesn't apply to sms only... I have no idea why, because it seems to work for emails: 

<img width="1060" alt="Capture d’écran, le 2022-09-29 à 14 20 45" src="https://user-images.githubusercontent.com/5230720/193112245-71ac7b72-5d20-47aa-86dd-0377d5716013.png">

2022-09-29 18:34 UTC, amazingphilippe commented
> I have no idea why, because it seems to work for emails:

There was an exception put in place only for sms. After looking at what we have in production, I noticed the FR was wrong there too. So it went under our radar since #480 !! 😲 

0 message texte envoyé
0 message texte restant
2 messages texte envoyés
2 messages texte restants

2022-10-04 16:48 UTC, andrewleith approved these changes
Left a question for you and Phil in the slack thread about wording. 

Just a question below about what you put in `conftest`, but other than that good to go.

2022-10-04 16:48 UTC, andrewleith commented on tests/conftest.py
> +
What's this?

2022-10-04 16:48 UTC, andrewleith commented on tests/app/main/views/test_dashboard.py
> +def test_daily_usage_section_shown(
Looks good! 👍

2022-10-04 17:19 UTC, smcmurtry commented on tests/conftest.py
> +
Whoops! I added that when I was trying to get the test debugger to work. I didn't mean to include it in this PR. Removing, thanks for catching that!

2022-10-04 18:01 UTC, amazingphilippe approved these changes
Current content seems to pluralize correct in both FR and EN!

2022-10-04 18:02 UTC, merged