Integration of qualtrics survey in staging only
cds-snc/notification-admin pull request #1361
Opened 2022-10-18 13:08 UTC by jimleroyer

# Summary | Résumé

This integrates the survey js widget into the admin UI. The widget will only show in non-production environments and for authenticated users.

🚩 At the moment of this writing, although the security content policies have been configured and the widget js executes on load, the div element to be generated does not work.

**TODO**: Try to add UI tests.

# Test instructions | Instructions pour tester la modification

* Load into the review environment and check if the widget works.
* UI tests loading javascript widget into headless browser.

2022-10-19 19:28 UTC, smcmurtry requested changes
In the review app, the feedback button text is showing up in french for me, when I have Notify displaying in English:
<img width="1475" alt="Screen Shot 2022-10-19 at 3 27 17 PM" src="https://user-images.githubusercontent.com/5498428/196785761-b56e98cb-ec7a-409f-8732-5cf9cce772cf.png">

2022-10-20 00:00 UTC, jimleroyer commented
Good find @smcmurtry . I investigated a bit and left comments on our internal Slack thread about this topic. 👍

2022-10-20 00:34 UTC, andrewleith commented on app/__init__.py
> +            )
These look about right to me, although I had to look each up 

- `script-src-elem` -> allows us to load scripts from qualtrics
- `connect-src` -> allows us it to fetch, do XMLHttpRequest, web sockets, etc. from qualtrics
- `frame-src` -> allows us to load an iframe hosted on qualtrics

---

`script-src-elem`:
> The HTTP [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) (CSP) script-src-elem directive specifies valid sources for JavaScript [<script>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) elements, but not inline script event handlers like onclick.

`connect-src`:
> The HTTP [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) (CSP) connect-src directive restricts the URLs which can be loaded using script interfaces.

`frame-src`:
> The HTTP [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) (CSP) frame-src directive specifies valid sources for nested browsing contexts loading using elements such as [<frame>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame) and [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe).

2022-10-21 12:45 UTC, andrewleith approved these changes
Survey still doesn't load in French when the app is in French (although the button correctly translates), but approving this anyway since you said that wasn't critical for this stage.

2022-10-21 12:45 UTC, andrewleith commented on tests/app/main/views/test_headers.py
> +        "'self' static.example.com *.canada.ca *.cdssandbox.xyz *.google-analytics.com *.googletagmanager.com *.notifications.service.gov.uk *.gstatic.com https://siteintercept.qualtrics.com data:;"
Looks good 👍

2022-10-21 13:25 UTC, jimleroyer commented
> Survey still doesn't load in French when the app is in French (although the button correctly translates), but approving this anyway since you said that wasn't critical for this stage.

Only the survey button on the side at this point should follow the language. Within the survey, there is a language selector. I don't know yet if we can get rid of that selector to follow the website selected lang or at least, select the right one by default. 

For these changes, the goal is to integrate Qualtrics to Notify in a safe env by deploying to staging so the Growth team can persue Qualtrics configuration. 👍

2022-10-21 13:32 UTC, smcmurtry approved these changes
I'm still seeing the button only in french, but maybe that can be fixed by some config on the qualtrics side

2022-10-21 15:11 UTC, merged