Fix 403 error for template preview and saves
cds-snc/notification-admin pull request #1426
Opened 2022-12-05 18:10 UTC by whabanks

# Summary | Résumé

Fix an issue where users received a 403 when attempting to edit and save a template where a variable had been added to the body of the template.

- Updated mock `template_json`'s `process_type` to `bulk`
- Updated a couple tests

# Test instructions | Instructions pour tester la modification

2022-12-07 19:07 UTC, jzbahrai commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
Is this correct? I was under the impression that an old template that was made under normal/ priority can't be viewed due to this line of code?

2022-12-07 19:22 UTC, whabanks commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
Good catch, something must have gone a bit haywire during merge/rebase. I'll fix this.

2022-12-07 20:09 UTC, jzbahrai commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
this is what we reverted here: https://github.com/cds-snc/notification-admin/pull/1425/files#diff-ab6836e1de1ae35fdbf46e68b40e71ca658c734751950019b2c08aba9c4084a1R714

and from how I read it - we are saying if the the template is not bulk, abort 403 ?

2022-12-07 20:35 UTC, smcmurtry requested changes

2022-12-07 20:35 UTC, smcmurtry commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
+1 @jzbahrai  I think we don't want to change this line. This will cause the 403 bug that we saw before: when a user edits a template that was created in the past, that has a normal priority.

2022-12-07 20:35 UTC, smcmurtry commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
Also, it will be normal for a platform admin to change a template from "bulk" priority to another priority. And then the user could no longer edit the template. 

I'm confused why the main branch is showing: `if form.process_type.data != "normal":` though. 
I think it should be: `if form.process_type.data != template["process_type"]:`
https://github.com/cds-snc/notification-admin/pull/1399/files#diff-ab6836e1de1ae35fdbf46e68b40e71ca658c734751950019b2c08aba9c4084a1L808

2022-12-07 20:35 UTC, smcmurtry commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
Looks like the revert PR reverted that line to the wrong logic: https://github.com/cds-snc/notification-admin/pull/1425/files#diff-ab6836e1de1ae35fdbf46e68b40e71ca658c734751950019b2c08aba9c4084a1R714

2022-12-07 21:36 UTC, whabanks commented on app/main/views/templates.py
> +        if form.process_type.data != TemplateProcessTypes.BULK.value:
Almost: If the template being created is not bulk, and the user is not an admin, abort 403. 
The problematic code giving us the 403 was in `edit_service_template` on L810, not here in `add_service_template`. 

This check should remain the same, we set the priority to Bulk by default and when they actually save the template we check to make sure that the `process_type` does not differ from the default before saving. We 403 if it does and they are not an admin.

The extra check on L810: `request.form.get("button_pressed") != "save"` was unnecessary and what caused the issue.

2022-12-08 16:44 UTC, smcmurtry approved these changes
Looks good!

2022-12-14 13:32 UTC, merged