CRM-related changes to Trial Account creation flow
cds-snc/notification-admin pull request #1491
Opened 2023-03-20 16:08 UTC by smcmurtry

# Summary | Résumé

This PR contains all of the UI changes for the CRM integration from https://github.com/cds-snc/notification-admin/pull/1483, but none of the Salesforce API calls, since the plan is to add those to `notification-api`.

This PR adds a "Step 3" to the Trial Service creation flow. This step is only visible if the feature flag `FF_SALESFORCE_CONTACT` is set to `True`. The organisation names are populated from [here](https://github.com/cds-snc/gc-organisations/tree/main/data). The new autocomplete "drop down" is actually a text input box.

The "organisation name" question is now hidden from the "go live" flow if the user has already provided us with an answer. 

I still need to add tests to this code.

# Test instructions | Instructions pour tester la modification

Design:
1. Log in to the review app using your staging account
2. Create a new trial service 
3. Review the new Step 3 page in English and French
4. Click the "Can't find my organisation" link to review the "other" step 3 page
5. Once the service is created, go to service settings and click "request to go live"
6. click "tell us about how you intend to use GC Notify"
7. verify that you are not asked for your organisation name again

Dev:
- Same steps as above, but run locally and verify that no changes are visible in the admin site if the feature flag is turned off (`FF_SALESFORCE_CONTACT=false` in .env)
- Also verify that the organisation name(s) are saved correctly in the new `organisation_notes` column in the `services` table in the db.
- Also test the new autocomplete component for accessibility (I have already done this but a second opinion is always good)

2023-03-20 19:27 UTC, adriannelee reviewed
Design - test instructions 1 to 4
- [ ] Not sure if this is how it should be, but when I change languages from Step 3, it takes me back to Step 1 (but keeps the info I input on Step 2)
- [ ] Same as ☝️ from FR to EN
- [ ] Step 3 says "This helps us better meet your needs" and clicking "Can't find your department or organisation?" says something similar "This information helps us understand how GC Notify is being used so we can better meet your needs." Should it say something else or maybe nothing? And actually, I wonder if we should be more explicit that this information won't be shown to their recipients, since we're asking them this after asking them information that **is** shown to recipients.
- [ ] Do we already have error messages for the input fields? When I tried to submit an empty form, it let me go to another screen and says "Sorry, we’re experiencing technical difficulties" and "Try again later."
- [ ] Same as ☝️ when I type an input for "Select your department or organisation" that's not a part of the list
- The error message "This field is required" works great for the "Name of your organization" field.

Design - test instructions 5 to 7
- Looks great!

2023-03-22 15:24 UTC, smcmurtry commented
> Not sure if this is how it should be, but when I change languages from Step 3, it takes me back to Step 1 (but keeps the info I input on Step 2)
> Same as ☝️ from FR to EN

@adriannelee Yeah that is an existing bug where changing the language moves you back to Step 1: https://youtu.be/lPpMy2uJDQ8
I'd prefer to address that one in a separate PR. The form info is saved so if a user goes back to a previous step, they don't lose information they've already entered.

2023-03-27 19:30 UTC, smcmurtry commented
> When I'm on the dropdown field, I don't get the example read to me. The second field on the page, I get the example read to me when I'm on the field.

@adriannelee nice find! the id I was using for that label wasn't correct. That issue should now be fixed

2023-03-27 19:40 UTC, smcmurtry commented
>  the first time something is typed into the dropdown field, the "Select your department or organisation" gets spelled out.

I wasn't able to reproduce this one. This is what I hear when going through the page: https://youtu.be/qlFF3XcWAWU

2023-03-27 19:52 UTC, patheard commented on app/main/views/add_service.py
> +        "form_cls": "",
Now that we're no longer selecting the type of org do we still need this to be dynamic with the `ORGANISIATION_STEP_DICT` below?

2023-03-27 20:10 UTC, smcmurtry commented on app/main/views/add_service.py
> +    if current_app.config["FF_SALESFORCE_CONTACT"] and current_step == STEP_ORGANISATION:
Hmm good question. In that case we could show the `step-enter-other-organisation.html` page that doesn't have the dropdown, so we still capture some organisation data to help us if the service requests to go live. That could make a good follow up PR.

2023-03-27 20:16 UTC, patheard commented on app/main/views/add_service.py
> +    if current_app.config["FF_SALESFORCE_CONTACT"] and current_step == STEP_ORGANISATION:
Nice, that would work!

2023-03-27 20:17 UTC, patheard commented on app/main/views/add_service.py
> +        "form_cls": "",
Ah gotcha, I'd forgotten about the case where your org isn't in the list.

2023-03-28 12:45 UTC, patheard commented
Test locally and in the PR review env and it's working as expected 🎉

2023-03-28 13:56 UTC, adriannelee commented
Huh, that's weird - I can't reproduce it either now 😅 @smcmurtry

2023-03-28 14:23 UTC, andrewleith requested changes
Looks great overall.  Very cleanly implemented, nice work!

A few questions below and one accessibility issue to be fixed

2023-03-28 14:23 UTC, andrewleith commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +      {{ autocomplete(form.parent_organisation_name, autocomplete_items_combined[current_lang], hint=_("For example: Treasury Board of Canada Secretariat")) }}
There seem to be many elements with the same id in the markup (`parent_organisation_name__assistiveHint`).  This technically fails HTML validation and the accessibility checker:
![image](https://user-images.githubusercontent.com/823749/228267823-352c06be-1161-44ee-8337-07f6d1ea2e21.png)

2023-03-28 14:23 UTC, andrewleith commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +        {{ _("Not on list?") }}
Since the "Not on list" link happens before the "other group names" input, this flows so that if you choose "not on list" you likely wont get the chance to enter the "other group name".  Was that intentional?

2023-03-28 18:12 UTC, smcmurtry commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +        {{ _("Not on list?") }}
Yes that is intentional. If you click "Not on list" then we just give one textbox to fill and ask "Enter name of your group".  Anything the user entered on the previous page is ignored. Then it will be a manual process to either create a new organisation for them if the service goes live, or figure out what existing organisation to assign the service to.

2023-03-28 18:57 UTC, smcmurtry commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +    {{ textbox(form.child_organisation_name, hint=_("For example: Canadian Digital Service"), maxlength=255) }}
Nice find! I added `required=false` to that `textbox` and that has fixed the issue

2023-03-28 19:22 UTC, smcmurtry commented on tests/app/main/views/test_add_service.py
> +def test_wizard_flow_with_step_3b_should_create_service(
Added some more tests around invalid data here: https://github.com/cds-snc/notification-admin/pull/1491/commits/ee52e96ebd7df8836bb552d5f8bfee39f1ac0cd9

2023-03-28 19:40 UTC, smcmurtry commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +      {{ autocomplete(form.parent_organisation_name, autocomplete_items_combined[current_lang], hint=_("For example: Treasury Board of Canada Secretariat")) }}
Okay it looks like the 2 elements with the same id are:
Hint 1:
```
<span id="parent_organisation_name__assistiveHint" class="form-hint">
  For example: Treasury Board of Canada Secretariat
</span>
```

and Hint 2:
```
<span id="parent_organisation_name__assistiveHint" style="display: none;">
  When autocomplete results are available use up and down arrows to review and enter to select.  
  Touch device users, explore by touch or with swipe gestures.
</span>
```

Hint 1 is from me and Hint 2 is an invisible hint that comes packaged with the autocomplete component. 

The fix for this would be to change the id of Hint 1, and update the `aria-describedby` attribute on the form field to [include the ids of both labels](https://stackoverflow.com/questions/53398842/can-i-reference-multiple-elements-using-aria-describedby). 

But unfortunately I can't update the `aria-describedby` attribute on the form because that is set internally in the accessible autocomplete component 😞 

And if I change the id of Hint 1 then it won't be referenced in the `aria-describedby` attribute on the form field, so we would re-introduce the problem that Adrianne described above:
> When I'm on the dropdown field, I don't get the example read to me. The second field on the page, I get the example read to me when I'm on the field.

2023-03-28 19:52 UTC, smcmurtry commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +      {{ autocomplete(form.parent_organisation_name, autocomplete_items_combined[current_lang], hint=_("For example: Treasury Board of Canada Secretariat")) }}
AXE is flagging this as a "critical" issue so I've changed the id to resolve that.

2023-03-29 11:21 UTC, andrewleith commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +      {{ autocomplete(form.parent_organisation_name, autocomplete_items_combined[current_lang], hint=_("For example: Treasury Board of Canada Secretariat")) }}
What was the behaviour when the 2 had the same id? If you want this read by a screen reader you could also just move in inside the label and not use `aria-describedby`

2023-03-29 11:22 UTC, andrewleith commented on app/templates/partials/add-service/step-enter-combined-organisation.html
> +    {{ textbox(form.child_organisation_name, hint=_("For example: Canadian Digital Service"), maxlength=255) }}
Looks good!

2023-03-29 11:24 UTC, andrewleith approved these changes
LGTM.  Approving, just a  question about the behaviour you were going for with the `aria-describedby`.

2023-03-29 13:45 UTC, merged