style: make the go-live content well padding more consistent
cds-snc/notification-admin pull request #1513
Opened 2023-04-03 17:45 UTC by andrewleith

# Summary | Résumé
This PR makes the padding in the go live content well more consistent.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/823749/229586598-a800e76e-3dcf-4fee-8eb1-949add30d116.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/823749/229586932-e1b976d1-46d6-406d-848f-daf7e157f9de.png">

2023-04-03 18:45 UTC, amazingphilippe commented
We could flip to a column direction on mobile, or even on all breakpoints. We'd have much more space for the paragraph, and it would be easier to read. 

Changes I made in the browser for the following screenshots:
1. Moved the anchor tag outside of the p tag
2. Moved the h2 inside the flex container
3. Added the `space-y-gutterHalf` spacer utility to the flex container
4. Also added `flex-col` to the container. 

<img width="1112" alt="Capture d’écran, le 2023-04-03 à 14 39 33" src="https://user-images.githubusercontent.com/5230720/229597938-3fed3375-b865-4c78-adc1-4cf5976136ed.png">

If we want to keep the row layout, we can do the following

1. Keep the h2 outside the container
2. Add `mt-gutterHalf` and `flex-col lg:flex-row items-baseline` to the container

If we feel really fancy, we could even add some css for `align-items: last-baseline`

![Capture d’écran 2023-04-03 à 14 44 54](https://user-images.githubusercontent.com/5230720/229598969-e363e6dd-4383-4411-a49c-b58ba5b1213c.png)

2023-04-04 19:54 UTC, andrewleith commented
@amazingphilippe I've added the changes you asked for, let me know if I understood correctly! :)

2023-04-05 15:00 UTC, amazingphilippe requested changes
3 Small changes and then lgtm!

2023-04-05 15:00 UTC, amazingphilippe commented on app/templates/views/service-settings.html
> +              <p class="flex-1 self-center mr-10 mb-0">
We should remove `self center` from the classes

2023-04-06 13:10 UTC, andrewleith commented
Removing that P tag somehow causes a test to fail, even though it isn't happening locally.  Not sure what is going on here.

2023-04-06 13:52 UTC, amazingphilippe commented
We can fix the test. The test is trying to select the anchor inside of a paragraph tags:

https://github.com/cds-snc/notification-admin/actions/runs/4621007615/jobs/8172370312#step:9:808

2023-04-06 16:36 UTC, andrewleith commented
> We can fix the test. The test is trying to select the anchor inside of a paragraph tags:
> 
> https://github.com/cds-snc/notification-admin/actions/runs/4621007615/jobs/8172370312#step:9:808
> 
> Instead of targeting `main p`, we could also add a test-id to the go-live box, to make it easier to select and make sure things don't break.

Yep for sure - except the test was passing locally for some reason even with the same selector so I was trying to do a sanity check here.  I can try the test-id, but after that I think we are spending too much time here.

2023-04-06 17:42 UTC, andrewleith commented
Good call on the testid @amazingphilippe, that takes the arbitrary HTML structure out of the test.  Everything is passing now!

2023-04-06 18:11 UTC, amazingphilippe approved these changes
Looks really good! 
We should bring this testing methodology up with the other devs

2023-04-12 17:50 UTC, merged