Feat/br review email problems
cds-snc/notification-admin pull request #1531
Opened 2023-04-18 20:10 UTC by andrewleith

# Summary | Résumé

This PR adds the "review email problems" and the "find and fix email problems" features to the dashboard.

2023-04-20 17:52 UTC, andrewleith commented on app/templates/components/is-problem-email.html
> +    <span style="color: #b10e1e" class="text-red">{{ _('Yes') }}</span>
@amazingphilippe, is there a way I can use a standardized color value here?  I tried with `text-red` but it didn't work...

2023-04-20 17:53 UTC, andrewleith commented on app/templates/views/activity/notifications.html
> +      {% set heading_3 = _('Status') %}
@amazingphilippe, do you know if I can get this heading to align right somehow?

2023-04-20 18:08 UTC, amazingphilippe commented on app/templates/views/activity/notifications.html
> +      {% set heading_3 = _('Status') %}
I think you could wrap the label into the `right_aligned_field_heading(text)` component!

2023-04-20 18:12 UTC, amazingphilippe commented on app/templates/components/is-problem-email.html
> +    <span style="color: #b10e1e" class="text-red">{{ _('Yes') }}</span>
`text-red` will work, but I think you'll have to compile tailwind, since we never used it as a utility class!

2023-04-20 19:33 UTC, andrewleith commented on app/templates/views/activity/notifications.html
> +      {% set heading_3 = _('Status') %}
Amazing! Thanks!

2023-04-20 19:36 UTC, andrewleith commented on app/templates/components/is-problem-email.html
> +    <span style="color: #b10e1e" class="text-red">{{ _('Yes') }}</span>
I could have sworn I recompiled it, but clearly not because that worked!  Thank you again! 🙇

2023-04-20 20:08 UTC, whabanks commented
Noticed a few inconsistent behaviours with the status ribbons. Tested both locally and in the review env.

![image](https://user-images.githubusercontent.com/7444334/233476398-9725db05-7913-4708-abf4-c9ac8b656f72.png)

2023-04-20 20:51 UTC, whabanks commented
On the View Job page when selecting the `Only show problem addresses` check box it becomes unchecked after refreshing and the `Failed` section on top is now highlighted.
[Uncheck + no Highlight](https://user-images.githubusercontent.com/7444334/233483868-48dceae2-fd9e-4ece-9e13-666b78c74101.webm)
If we navigate to the Job page via the `Review Addresses` page, the `Failed` section is highlighted.
[Highlighted when navigating from review page](https://user-images.githubusercontent.com/7444334/233484828-d600d63c-c031-40be-a972-4a4bb52bf203.webm)

2023-04-21 11:39 UTC, andrewleith commented
> Noticed a few inconsistent behaviours with the status ribbons. Tested both locally and in the review env.
> 
> ![image](https://user-images.githubusercontent.com/7444334/233476398-9725db05-7913-4708-abf4-c9ac8b656f72.png)

Good eye @whabanks.  @amazingphilippe what do you prefer the behaviour should be here?  Should these be links like the text message block? or go nowhere like email ones?

2023-04-21 11:48 UTC, andrewleith commented
> On the View Job page when selecting the `Only show problem addresses` check box it becomes unchecked after refreshing and the `Failed` section on top is not highlighted. [Uncheck + no Highlight](https://user-images.githubusercontent.com/7444334/233483868-48dceae2-fd9e-4ece-9e13-666b78c74101.webm) If we navigate to the Job page via the `Review Addresses` page, the `Failed` section is highlighted. [Highlighted when navigating from review page](https://user-images.githubusercontent.com/7444334/233484828-d600d63c-c031-40be-a972-4a4bb52bf203.webm)

For the uncheck issue, is it possible you need to force refresh the page to get the latest js?  I am not seeing the box uncheck here locally or in the PR review environment 🤔 Can you look at your URL when this happens?  The way this functionality works is when you click the checkbox it adds some additional parameters to the query string and reloads the page, so refreshing the page should not affect the results here.

For the filtering issue, @amazingphilippe mentioned this to me yesterday also.  The filters are mutually exclusive right now, as the problem emails are actually a subset of the failed requests.  We *could* keep the failed filter highlighted when people click the checkbox, but the number displayed there may or may not be the number of notifications we actually display in that case.  Perhaps this requires some discussion.

2023-04-21 20:09 UTC, andrewleith commented on app/templates/components/big-number.html
> +                <i aria-hidden="true" class="p-1 fa-solid {% if danger_zone %}fa-circle-exclamation{% else %}{% endif %}"></i>
Yes, I think you're right nice catch!

2023-04-24 14:18 UTC, whabanks commented
>We could keep the failed filter highlighted when people click the checkbox, but the number displayed there may or may not be the number of notifications we actually display in that case. Perhaps this requires some discussion.
Good point Andrew, highlighting this with the check box ticked is confusing now that I look more closely at it.

2023-04-24 14:20 UTC, whabanks requested changes
LGTM, once we've come to a consensus on the link behaviours and the filter highlighting then we are good to go!

2023-04-24 15:49 UTC, andrewleith commented on app/templates/views/dashboard/review-email-list.html
> +                <i aria-hidden="true" class="p-1 fa-solid fa-fas fa-circle-exclamation"></i>
Amazing! That was bothering me but I couldnt bend it to my will! I'll try this :)

2023-04-24 15:50 UTC, amazingphilippe commented on app/templates/views/dashboard/review-email-list.html
> +                <i aria-hidden="true" class="p-1 fa-solid fa-fas fa-circle-exclamation"></i>
Removing `p-1` altogether also fixes center alignment. But I can suggest something else to fix this and another problem:

Right now, we could make this banner more robust by placing the icon in its container, rather than the paragraph. This would help align the icon when lines wrap. 

Current:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/5230720/234049255-c587f00e-b958-4833-b0ce-6ad28f88d7b0.png">

If we place the icon as a direct child of the container. There are lots of margin and padding cleanup to do. I've also screenshot the padding structure needed.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/5230720/234049637-2e8c01b7-dfc4-4c11-814e-16b42c114d65.png">
<img width="393" alt="image" src="https://user-images.githubusercontent.com/5230720/234049657-2461ca2d-5bd2-4457-8342-05013f5255f1.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/5230720/234049668-b90415fa-1bb3-4468-9476-1685ee6b58ea.png">

2023-04-24 15:57 UTC, andrewleith commented on app/main/views/dashboard.py
> +    if total_sent < current_app.config["BR_DISPLAY_VOLUME_MINIMUM"]:
This behaviour is tied to that minimum value, which in this environment appears not to be set 😱 I just set it to 10.  Let me know if it behaves as you expect.

2023-04-24 15:58 UTC, andrewleith commented on app/main/views/dashboard.py
> +    if total_sent < current_app.config["BR_DISPLAY_VOLUME_MINIMUM"]:
Actually, my bad, this one isn't an environment variable, just a config value, and its set to 1000.

2023-04-24 17:28 UTC, amazingphilippe requested changes
Some tweaks, but mainly including the translations now that we have them!

2023-04-24 17:30 UTC, amazingphilippe commented on app/templates/views/dashboard/review-email-list.html
> +                <i aria-hidden="true" class="p-1 fa-solid fa-fas fa-circle-exclamation"></i>
I'm using the `-gutterHalf` value for both the box padding, and the icon inline-end-padding

2023-04-24 18:21 UTC, amazingphilippe commented
Looking at the screenshots above: The status box should be turning red. And there is no content in the "past 24h" section

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/5230720/234082712-404e4ad4-8eac-4797-9efd-7d763cb1c84f.png">

2023-04-24 18:58 UTC, andrewleith commented on app/templates/views/dashboard/review-email-list.html
> +                <i aria-hidden="true" class="p-1 fa-solid fa-fas fa-circle-exclamation"></i>
Do you want to suggest the change if you have it? 😉

2023-04-24 18:59 UTC, andrewleith commented on app/templates/components/big-number.html
> +                <span class="underline font-bold">{{_('Review reports') }}</span>
Yes there are still many outstanding translations.. have they come back from the translation team?

2023-04-24 19:00 UTC, andrewleith commented
> Looking at the screenshots above: ~1. The status box should be turning red.~ Just saw the comment about config 2. There is no content in the "past 24h" section
> 
> <img alt="image" width="1058" src="https://user-images.githubusercontent.com/5230720/234082712-404e4ad4-8eac-4797-9efd-7d763cb1c84f.png">

There is a known issue where the design of the "review problem email" page doesn't take into account anything other than bulk sends - this was discussed and decided to be addressed in the next version.  Is it possible all your problem emails were sent as one-off's?

2023-04-25 11:36 UTC, andrewleith commented on app/statistics_utils.py
> +def get_formatted_percentage_zero_dp(x, tot):
No probably not, I can remove it.

2023-04-25 11:38 UTC, andrewleith commented on app/templates/views/dashboard/review-email-list.html
> +                <i aria-hidden="true" class="p-1 fa-solid fa-fas fa-circle-exclamation"></i>
```suggestion
                <i aria-hidden="true" class="px-1 fa-solid fa-fas fa-circle-exclamation"></i>
```

2023-04-25 11:40 UTC, andrewleith commented on app/assets/stylesheets/tailwind/components/big-number.css
> +    @apply no-underline opacity-75;
```suggestion
    @apply no-underline;
```

2023-04-25 11:41 UTC, andrewleith commented on app/assets/stylesheets/tailwind/components/big-number.css
> +    @apply no-underline opacity-75;
```suggestion
    @apply no-underline;
```

2023-04-25 11:42 UTC, andrewleith commented on app/assets/stylesheets/tailwind/components/big-number.css
> +    @apply no-underline opacity-75;
Done.

2023-04-25 19:07 UTC, amazingphilippe commented
>  Is it possible all your problem emails were sent as one-off's?

Yes. This is exactly what is happening!

2023-04-25 19:08 UTC, amazingphilippe commented on app/templates/views/dashboard/review-email-list.html
> +                <i aria-hidden="true" class="p-1 fa-solid fa-fas fa-circle-exclamation"></i>
Yep! Sounds good. I don't have super detailed changes to share here and now, but I can work on a tiny follow up PR!

2023-04-25 19:24 UTC, amazingphilippe requested changes
2 tiny fixes! Almost there!

2023-04-25 19:24 UTC, amazingphilippe commented on app/templates/components/problem-email-checkbox.html
> +        <h2 class="heading-medium">Filters</h2>
Missing translation function call! And should be singular. 

Which is good news because we have `"Filter","Filtrer"` (singular) in our csv!

2023-04-25 19:24 UTC, amazingphilippe commented on app/translations/csv/fr.csv
> +"in transit","FR: in transit"
This one is missing! `"in transit","envoi en cours"`

2023-04-26 11:31 UTC, andrewleith commented on app/templates/components/problem-email-checkbox.html
> +        <h2 class="heading-medium">Filters</h2>
Good eye, thanks!

2023-04-26 11:31 UTC, andrewleith commented on app/translations/csv/fr.csv
> +"in transit","FR: in transit"
Fixed!

2023-04-26 12:00 UTC, andrewleith commented on app/assets/javascripts/notificationsReports.js
> +      console.log("cb chaned", $pe_checkbox.is(":checked"));
remove debugging code
```suggestion
```

2023-04-26 12:03 UTC, andrewleith commented on app/statistics_utils.py
> +def get_formatted_percentage_zero_dp(x, tot):
Done!

2023-04-26 12:06 UTC, andrewleith commented on app/main/views/dashboard.py
> +    if total_sent < current_app.config["BR_DISPLAY_VOLUME_MINIMUM"]:
I think this is working as designed, but if @whabanks if you still think there is an issue here please let me know!

2023-04-26 13:55 UTC, amazingphilippe approved these changes
Design looks good to me!

2023-04-26 17:53 UTC, whabanks commented on app/main/views/dashboard.py
> +    if total_sent < current_app.config["BR_DISPLAY_VOLUME_MINIMUM"]:
Right, the threshold! Forgot all about that. I do think it could be confusing to the user if they see green and a percentage greater than 10%, then they start to see red once they cross the threshold. Perhaps something we can revisit in v1.5/v2?

2023-04-26 17:54 UTC, whabanks approved these changes

2023-04-26 18:20 UTC, smcmurtry approved these changes
Tested the review app sending real CSVs and everything seems to work as I would have expected. Code looks good too. Nice work @andrewleith!!

2023-04-26 18:20 UTC, smcmurtry commented on app/config.py
> +    BR_CRITICAL_PERCENTAGE = 10
Let's change these to 0.05 and 0.1 in a future PR (maybe for the 1.5 release?) to align with the values we're using in notification-utils: https://github.com/cds-snc/notification-utils/blob/main/notifications_utils/clients/redis/bounce_rate.py#L8-L9

2023-04-26 18:20 UTC, smcmurtry commented on app/models/enum/bounce_rate_status.py
nice!

2023-04-26 23:53 UTC, andrewleith commented on app/config.py
> +    BR_CRITICAL_PERCENTAGE = 10
When we update admin to use the redis bounce rate client this may become unnecessary, so let's keep that in mind as well (and aim for it if possible)!

2023-04-26 23:59 UTC, andrewleith commented on app/models/enum/bounce_rate_status.py
This looks almost too good....

🔬 

Yep, @whabanks wrote this 😅

2023-04-27 16:24 UTC, merged