Increase size of 'Sign in' button in top right nav
cds-snc/notification-admin pull request #1574
Opened 2023-06-06 19:37 UTC by whabanks

# Summary | Résumé
I could not find any tools to test that the addition of an `aria-label` on the sign in button will correct the issue with the sign in link not "responding" to voice commands via Dragon Naturally Speaking. 

# Test instructions | Instructions pour tester la modification

1. Visit the home page, note that the size of the "Sign in" link text is increased

2023-06-07 17:23 UTC, amazingphilippe requested changes
A few design things and a translation!

Another thing for design: Could we check this account menu button and make sure we also apply the font size increase?

<img width="352" alt="image" src="https://github.com/cds-snc/notification-admin/assets/5230720/16f9083b-9940-4d64-9559-2bab9ba75b48">

We could also look into the mobile version of the menu, which is in a completely different file. I think it still has a smaller font size. 

<img width="387" alt="Capture d’écran, le 2023-06-07 à 13 22 32" src="https://github.com/cds-snc/notification-admin/assets/5230720/c1c5a7de-1b88-4002-b4de-4da332dcb130">

2023-06-07 17:23 UTC, amazingphilippe commented on app/translations/csv/fr.csv
> +"Sign in to GC Notify","Se connecter à GC Notify"
In French, let's have "Se connecter à Notification GC"

2023-06-07 17:23 UTC, amazingphilippe commented on app/templates/partials/nav/gc_header.html
> +              class='text-base',
Two things:

1. We can modify the macro directly, as we use it for the language toggle and back to top link on mobile. Both of these would benefit from the size increase. 
2. Let's use the confusingly named `text-smaller` (1.9rem) utility class to match the larger font sizes we use by default (except on buttons for some reason?).

2023-06-08 15:31 UTC, whabanks commented on app/templates/partials/nav/gc_header.html
> +              class='text-base',
Changes made! Thanks for pointing this out it's a much better idea.

2023-06-08 15:31 UTC, whabanks commented on app/translations/csv/fr.csv
> +"Sign in to GC Notify","Se connecter à GC Notify"
Corrected!

2023-06-08 15:34 UTC, whabanks commented
I also made these changes:
- Increased the account menu text size
- Increase the account menu items text size
- Increased text sizes for sign in links, and account menu items on mobile to match the text size used for the items displayed in the `Menu` navigation.

2023-06-08 16:58 UTC, merged