Feat/add daily usage widget
cds-snc/notification-admin pull request #1658
Opened 2023-09-07 17:58 UTC by andrewleith

# Summary | Résumé

This PR adds a new component for daily limits and uses them on the dashboard to display both email and SMS limits:

![image](https://github.com/cds-snc/notification-admin/assets/823749/f50446d4-c9f4-433b-9a77-adcb88f86986)

Note: a bug was found where the daily stats used in the dashboard are not based off of midnight UTC like other places in the app.  This will be fixed in a follow-up PR.

2023-09-08 20:22 UTC, smcmurtry requested changes
Overall this looks great! The component resizes nicely on different screen sizes. I have a couple requests/suggestions before merging.

2023-09-08 20:22 UTC, smcmurtry commented on app/templates/views/dashboard/dashboard.html
> +    {{ ajax_block(partials, updates_url, 'daily_totals', interval=5) }}
Since we haven't fixed the bug with the data yet - could you revert this one change? That way we could merge this PR but the new widgets won't be visible on the dashboard. Then we can make them visible once we fix the data.

2023-09-08 20:22 UTC, smcmurtry commented on app/templates/components/remaining-messages.html
> +    <div class="rm-header mb-2">{{ header }}</div>
I did some testing of this component with a screen reader: https://youtu.be/y-hsXyCGuck
Would it be possible to make this header get read out along with the numbers below? Could be accomplished by making it an aria-label? I'm thinking it would be nice to have the screenreader read it like: "2 of 5 emails" instead of "emails"... "2 of 5".

2023-09-08 20:22 UTC, smcmurtry commented on app/templates/components/remaining-messages.html
> +    <div class="rm-header mb-2">{{ header }}</div>
I also tested what happens when you are near the limit: https://youtu.be/_LeUcFtlgps

The hidden text is getting read out correctly - very nice! 

One suggestion - it might be better for it to say "near daily email limit" instead of "near daily limit"

2023-09-11 11:46 UTC, andrewleith commented on app/templates/views/dashboard/dashboard.html
> +    {{ ajax_block(partials, updates_url, 'daily_totals', interval=5) }}
Yes, can do.  I will leave that until last so @amazingphilippe can take a look at the UI implementation first (if he wants to!)

2023-09-11 11:46 UTC, andrewleith commented on app/templates/components/remaining-messages.html
> +    <div class="rm-header mb-2">{{ header }}</div>
Great ideas, I'll incorporate those now.

2023-09-11 12:11 UTC, andrewleith commented on app/templates/components/remaining-messages.html
> +    <div class="rm-header mb-2">{{ header }}</div>
Ok I went a slightly different route for implementation but should arrive at the same result.  Instead of trying `aria-label` or `aria-describedby` I just added the contextual piece of info (i.e `emails`/`text messages`) into the message itself. After testing in voice over, I felt that a more direct message would stand out better, so I changed it to:
"1900 of 2000 emails - you are nearing the daily emails limit"

2023-09-12 14:30 UTC, amazingphilippe approved these changes
Looks good to me!

2023-09-18 15:37 UTC, merged