A11y/fix titles add emptystate
cds-snc/notification-admin pull request #1696
Opened 2023-11-02 12:52 UTC by andrewleith

# Summary | Résumé

This PR fixes the titles on the notifications reports pages and adds some empty states to various pages.  Changes:
1. Update main notification report title; add empty state (`/services/{sid}/notifications/email?status=sending,delivered,failed`)
2. Update bulk notification report title (`/services/{sid}/jobs/{jid}`) 
3. Add empty state for sent messages on bulk screen (`/services/{sid}/jobs`)
4. Add empty state for scheduled messages on bulk screen (`/services/{sid}/jobs`)

2023-11-02 20:37 UTC, jimleroyer commented on app/assets/images/empty-bird.svg
Love the bird 🐦

2023-11-06 20:17 UTC, amazingphilippe requested changes
3 areas where I think we need changes or better design docs.

1. The jobs page `{sid}/jobs`
If there are no scheduled jobs, don’t show “sent messages” section at all, unless some have been sent in the past. Ideally we only need one empty state per screen
![image](https://github.com/cds-snc/notification-admin/assets/5230720/1c038253-a5b6-485b-8302-447523d728de)

2. The delivery report for a scheduled job that hasn't been sent yet
This screen doesn’t work as well for scheduled jobs. We can design something else that would work better. 
Delivery report seems out of place: nothing has been sent yet.
I don’t know what is being sent, maybe we could get a list, like on the review page?
We can think of a better h1
We can remove the pill nav
We can architect the content a bit more clearly. 
We can create familiarity with the delivery report by putting some info near the heading: scheduled by, starting, origin
![image](https://github.com/cds-snc/notification-admin/assets/5230720/fdda294c-9e14-4d37-a568-bdbdf60ac44c)

3. The delivery report after the retention period
Not quite the right content.
List: sent by, started, origin
Tweak screen for after the 7 days. This can communicate the same broad strokes, but the pill nav serves no purpose
![image](https://github.com/cds-snc/notification-admin/assets/5230720/2c316a83-6b3e-4bb0-83a6-b80a0605c963)

2023-11-07 13:09 UTC, andrewleith commented
> 3 areas where I think we need changes or better design docs.
> 
> 1. The jobs page `{sid}/jobs`
>    If there are no scheduled jobs, don’t show “sent messages” section at all, unless some have been sent in the past. Ideally we only need one empty state per screen

Can the user get to this page when its in this state? When there are no jobs scheduled and none have been sent, this section doesnt appear on the dashboard at all as far as I'm aware.  If that is the case, I don't think we need to spend time on this.

> 2. The delivery report for a scheduled job that hasn't been sent yet
>    This screen doesn’t work as well for scheduled jobs. We can design something else that would work better.
>    Delivery report seems out of place: nothing has been sent yet.
>    I don’t know what is being sent, maybe we could get a list, like on the review page?
>    We can think of a better h1
>    We can remove the pill nav
>    We can architect the content a bit more clearly.
>    We can create familiarity with the delivery report by putting some info near the heading: scheduled by, starting, origin

Yeah this doesn't quite make sense.  The page title should be "Scheduled send" when it hasn't been sent yet to be consistent with the main dashboard and I agree the pill nav should be axed.  How do you want to lay this out?  There are 5 piece of info we have to display here:
1. who uploaded it
2. the file name
3. date it was uploaded
4. date its scheduled for
5. template used

> 3. The delivery report after the retention period
>    Not quite the right content.
>    List: sent by, started, origin
>    Tweak screen for after the 7 days. This can communicate the same broad strokes, but the pill nav serves no purpose
>    ![image](https://user-images.githubusercontent.com/5230720/280836731-2c316a83-6b3e-4bb0-83a6-b80a0605c963.png)

So we have all the totals but can't click through because we don't have the details?

2023-11-21 13:53 UTC, amazingphilippe requested changes
A few observations
- The delivery report info at the top should be expanded so that we have the file name, or API request name somewhere. Similar to the scheduled messages screen.
<img width="1185" alt="Capture d’écran, le 2023-11-21 à 08 46 38" src="https://github.com/cds-snc/notification-admin/assets/5230720/5dda4368-9177-4ca9-9e33-0baeb9b5a997">
- If we use a table layout, we can drop the colons
<img width="1157" alt="Capture d’écran, le 2023-11-21 à 08 44 48" src="https://github.com/cds-snc/notification-admin/assets/5230720/92a182f8-1377-40ae-b0bc-01577e057ee5">
- And we should have the missing transaltions in the coming days. 

Otherwise looks good!

2023-11-27 16:40 UTC, whabanks approved these changes
LGTM overall! Just a couple minor comments / questions.

2023-11-27 20:41 UTC, andrewleith commented on app/main/views/jobs.py
> +    svc_retention_days = 7 if len(svc_retention_days) == 0 else svc_retention_days[0]
For the hard coded 7?  Yeah, you are right, this should be the default, `ACTIVITY_STATS_LIMIT_DAYS`.  I'll fix this!

2023-11-30 20:13 UTC, amazingphilippe reviewed
Just one note about the title of the single scheduled job screen. And what we discussed about the delivery report details logic. After this we're good!

2023-11-30 20:13 UTC, amazingphilippe commented on app/templates/views/jobs/job.html
> +    {{ _('Scheduled messages') }}
Current: title will be "Envois programmés" (plural form)
Designs: title should be "Envoi programmé" (singular)

I'm not sure if this will conflict with other instances of this string. If this is the only instance, then we can make the change in translation csv.

2023-12-07 14:42 UTC, amazingphilippe commented on app/templates/views/jobs/job.html
> +    {{ _('Scheduled messages') }}
Not sure! French focuses more on a job, English focuses more on the messages. Both work!

2023-12-07 19:28 UTC, amazingphilippe approved these changes
Review app isn't showing the change, but looking at the fr csv file I can see the correct translation, so I'll just approve this!

2023-12-11 18:28 UTC, merged