Refactor scheduled message page to use a table
cds-snc/notification-admin pull request #1796
Opened 2024-04-04 20:43 UTC by whabanks

# Summary | Résumé
This PR migrates the data table in scheduled messages status page to actually use a table instead of just a series of divs formatted to look like a table.

# Test instructions | Instructions pour tester la modification
WIP

2024-04-04 20:44 UTC, whabanks commented on app/templates/views/jobs/job.html
> -
Non-changing formatting changes below :)

2024-04-10 15:31 UTC, amazingphilippe requested changes
Some changes need to have proper data headers, but good start!

2024-04-10 15:31 UTC, amazingphilippe commented on app/templates/views/jobs/job.html
> +        {% set caption = _("Scheduled message") %}
Missing an "s"!

2024-04-10 15:31 UTC, amazingphilippe commented on app/templates/views/jobs/job.html
> +        {% set h_sending_to = _("Sending to") %}
There should be 2 TH in this table. These seem to create a row of th above, but they don'T match the table structure. 

I don't know if there is a way to flip the axis with this table component. If we can't flip the axis, we should come up with labels for the 2 columns. Something as simple as "Label" and  "Value", which we already have translations for

2024-04-10 15:31 UTC, amazingphilippe commented on app/templates/views/jobs/job.html
> +            {{ text_field(h_scheduled_by) }}
I think you could also call `row_heading()` instead of `text_field()` to create headings scoped to the row (this comment applies to the rows below too). In this case, I think we should also remove the header row in my comment above

2024-04-10 15:31 UTC, amazingphilippe commented on app/templates/components/table.html
> +  <tr class="table-row {{ classes if classes }}" {% if id and id is string %}id="cds{{id}}"{% endif %}>
Neat!

2024-04-10 15:31 UTC, amazingphilippe commented on app/templates/components/table.html
> +{% macro field(align='left', status='', cell_width=None, border=True) -%}
Cool addition to be able to choose the with of a col! We should test on all the breakpoints

2024-04-11 17:20 UTC, whabanks commented on app/templates/views/jobs/job.html
> +        {% set h_sending_to = _("Sending to") %}
I was able to flip the axis of the table using `row_heading` instead of `text_field` in the first column. I also removed the headings that did not map correctly with the table instead of using `Label` and `Value`. 

One caveat though, the current macro will still render a `thead` and an empty `tr` on the table.
![image](https://github.com/cds-snc/notification-admin/assets/7444334/0ed9f8bd-362a-46ac-9cb8-687268973227)

If this is an issue, we could either:
1. Edit the macro to not render a `thead` if we do not pass in any header items
2. Use your suggestion of setting `label` and `value` headers.

2024-04-11 17:20 UTC, whabanks commented on app/templates/views/jobs/job.html
> +            {{ text_field(h_scheduled_by) }}
Done!

2024-04-11 17:21 UTC, whabanks commented on app/templates/views/jobs/job.html
> +        {% set caption = _("Scheduled message") %}
Fixed!

2024-04-16 13:06 UTC, amazingphilippe commented on app/templates/views/jobs/job.html
> +        {% set h_sending_to = _("Sending to") %}
Lets label with "Label" and "Value" as this is what we seem to do on other tables!

2024-04-17 15:26 UTC, amazingphilippe commented on app/templates/components/table.html
>      <thead class="table-field-headings{% if field_headings_visible %}-visible{% endif %}">
I read into it a bit more, and if we'd like to have tables with headers in the first column, we need to get rid of the `<thead>`
https://www.w3.org/WAI/tutorials/tables/one-header/#table-with-header-cells-in-the-first-column-only

I'm thinking we could wrap the `<thead>` in an if statement similar to `{% if field_headings | length > 0 %}`. That way we can (intentionally) remove the `thead` when using the `row_heading` macro.

2024-04-17 19:34 UTC, whabanks commented on app/templates/components/table.html
>      <thead class="table-field-headings{% if field_headings_visible %}-visible{% endif %}">
I updated the `mapping_table` macro as suggested. We should no longer be rendering a `thead` if `field_headings` has no elements in it.

2024-04-17 20:07 UTC, amazingphilippe approved these changes
Looks good to me!

2024-04-24 19:21 UTC, merged