simplify file_upload components and file upload in branding form
cds-snc/notification-admin pull request #1807
Opened 2024-04-16 15:01 UTC by amazingphilippe

# Summary | Résumé

Fundamentally reconsiders how we do file uploaders.

More native, with a bit of css.

Can't be localized: The browser's default file uploader is sort of a web component, and you can't slot in your own text strings. 

# Test instructions | Instructions pour tester la modification

1. Take a look at _styleguide, or other screens containing a file upload button.

2024-04-16 15:03 UTC, amazingphilippe commented on app/templates/components/file-upload.html
> +      {{ button_text }}
Moving the button text above the button, since we can't customize the native button's text

2024-04-16 15:05 UTC, amazingphilippe commented on app/templates/views/email-branding/branding-request.html
> +            <div class="file-upload-extra pt-4 preview font-normal relative" data-testid="brand_fileinfo">
Just concatenating those styles a bit, it helps keep things consistent with how I grouped the file upload elements with a border:
<img width="511" alt="image" src="https://github.com/cds-snc/notification-admin/assets/5230720/2688ddd6-2de6-4a93-9bed-0c95c9ec9eab">

2024-04-16 15:05 UTC, amazingphilippe commented on app/templates/views/email-branding/branding-request.html
> +            <div class="file-upload-extra pt-4 preview font-normal relative" data-testid="brand_fileinfo">
Another example: 
<img width="469" alt="image" src="https://github.com/cds-snc/notification-admin/assets/5230720/0eebb07d-59ca-4f3b-a1ef-caf2864b84f5">

2024-04-16 18:06 UTC, andrewleith commented on app/templates/views/email-branding/branding-request.html
> +            <div class="file-upload-extra pt-4 preview font-normal relative" data-testid="brand_fileinfo">
Looks good. The file-uploader on the branding request page isn't actually in a component yet, is that what you were hoping to accomplish here?  

The idea for branding was to improve on it without messing with our existing one, until we can test it.  Want me to help turn it into a component we can do some fable tests on?

2024-04-16 18:11 UTC, amazingphilippe commented on app/templates/views/email-branding/branding-request.html
> +            <div class="file-upload-extra pt-4 preview font-normal relative" data-testid="brand_fileinfo">
Yeah! That's why I'm unsure to merge this or not. It might make sense to keep this as a PR to do testing.

Our current macro renders the whole `<form>`

In my mind it would make sense to have a sub macro with just the file input, and feed it to the current file_upload macro as well as within your branding form.

Lets leave this open for the time being! And revisit once we start Fable testing.

2024-04-16 19:13 UTC, andrewleith commented on app/templates/views/email-branding/branding-request.html
> +            <div class="file-upload-extra pt-4 preview font-normal relative" data-testid="brand_fileinfo">
Yeah, let's use this as a PR do to some testing.  We can add a simple testing route and try it out easy enough!

2024-05-29 14:18 UTC, andrewleith requested changes
Looks good to me overall.  The request branding page still works, although the missing `data-testid` will cause the tests to fail so just requesting that you add that back.

2024-05-29 14:29 UTC, whabanks requested changes
I noticed a couple of issues:
1. On the branding upload page I am unable to "click" the `File Upload` button with the keyboard both with and without a screen reader. 
2. When using a screen reader the `File Upload` button is not read out


https://github.com/cds-snc/notification-admin/assets/7444334/ea4fbadc-4f27-4999-b559-24ed90880332


3. On the `Prepare a spreadsheet` page the File upload button cannot be navigated to via the keyboard.
4. There's some extra hint text showing the mime types / file extensions accepted that I don't see captured in your original screen shots, was this an intentional change?

https://github.com/cds-snc/notification-admin/assets/7444334/06c7ee37-733e-4da2-a16d-ad0d077d93a2

2024-05-29 17:13 UTC, amazingphilippe commented on app/templates/views/email-branding/branding-request.html
> -                {{ form.file(**{ 'class': 'file-upload-field', 'accept': 'image/png', 'data_testid': 'brand_image', 'aria-labelledby': 'file-description', 'data-error-msg': _('You must select a file
I can add it back. The testid needs to be on the input element?

2024-05-29 17:49 UTC, amazingphilippe commented on app/templates/views/email-branding/branding-request.html
> -                {{ form.file(**{ 'class': 'file-upload-field', 'accept': 'image/png', 'data_testid': 'brand_image', 'aria-labelledby': 'file-description', 'data-error-msg': _('You must select a file
Added testid as file field optional attribute. defaults to `test_field-name`

2024-05-29 17:55 UTC, amazingphilippe commented
Yikes! Thanks Will for spotting these issues.

1. I've re-enabled to focus on the actual input. This will re-enable the default keyboard interaction.
2. I placed focus styles on `:focus-within` since our input is invisible. I had to rearrange a bit the label and other form group instructions. (which also solved another bug with the focus indicator on an invalid file input)
3. I've made sure to name the macro attributes when calling it. The `accept` was being interpolated to `hint`

2024-05-30 13:56 UTC, amazingphilippe commented
> 2\. When using a screen reader the `File Upload` button is not read out

I think this isn't fixed yet. I believe VoiceOver really dislikes having the file input inside the label, so I'll need to rethink the markup again.

2024-06-03 20:27 UTC, whabanks commented
Looking much better:
1. I can properly click on the `File Upload` button with the keyboard
2. I can use the `caps lock + arrow keys` combo to navigate to the `File Upload` button and it will read the label correctly, but does not read it if tabbed to the button
3. The mimetype list is not longer there 🚀

2024-06-04 13:04 UTC, amazingphilippe commented
@whabanks If you want to give it another go, I think the review app hadn't built properly. I merged with main and I believe issue 2 should be fixed!

2024-06-04 16:19 UTC, whabanks approved these changes
Looks great now, nice work! 🚀 

When it reads out the button, it has the phrase `required invalid data`, the `invalid data` seems redundant with the presence of `No file currently selected` but I don't think we really **need** to change it.

![image](https://github.com/cds-snc/notification-admin/assets/7444334/50eb7d50-9e04-4977-bad9-9a7d704ed009)

2024-06-04 18:25 UTC, amazingphilippe commented
> `invalid data` seems redundant with the presence of `No file currently selected`

I think this might be the nature of having dedicated descriptive text. Also, this also helps indicate why the data is invalid!

2024-06-10 15:46 UTC, andrewleith approved these changes
Looks great!  All tests are passing, we are good to go!

2024-06-10 18:47 UTC, merged