Changes to add/update/edit alt text logo
cds-snc/notification-admin pull request #1820
Opened 2024-04-25 16:23 UTC by jzbahrai

# Summary | Résumé

Changes to Add/ Edit alternative text in english and french.
Two pages are changed:
1. Upload Email Branding on the admin side
1. Branding Request (as submtited by end user)

# Test instructions | Instructions pour tester la modification

1. Upload a new brand through the Branding Request form page
1. Add alt text in en/ french on the Branding Upload page in admin

Requires this PR: https://github.com/cds-snc/notification-api/pull/2162

2024-05-01 17:58 UTC, whabanks commented
This may be unrelated to this work, but when I try to update an existing branding to add en/fr alt text with `No organisation ` selected SQLAlchemy in API complains about the `organisation_id` being `-1`:

```
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: "-1"
LINE 1: ...E email_branding SET colour=NULL, organisation_id='-1', alt_...
                                                             ^
[SQL: UPDATE email_branding SET colour=%(colour)s, organisation_id=%(organisation_id)s, alt_text_en=%(alt_text_en)s, alt_text_fr=%(alt_text_fr)s WHERE email_branding.id = %(email_branding_id)s]
[parameters: {'colour': None, 'organisation_id': '-1', 'alt_text_en': 'abc', 'alt_text_fr': 'bcb', 'email_branding_id': UUID('c90eff6c-fa2f-48f6-ac58-a589442b27ae')}]
```

2024-05-01 18:01 UTC, whabanks requested changes

2024-05-01 18:01 UTC, whabanks commented on app/assets/javascripts/formValidateRequired.js
> +(function () {
Nice work on this validation JS. It works really smoothly highlighting those required fields when you tab off them without filling them out 🎉

2024-05-02 14:40 UTC, andrewleith commented on app/templates/components/textbox.html
> +        {{ textbox(localized_field, localized_field.label.text, width='w-full', data_error_msg=localized_field.validators[0].message) }}
As per our meeting this morning, this is where we would need to add the `lang` attribute for whichever of these 2 inputs is not in the language of the current page.  For example, if the user is on the page in English, we would need to add `lang="fr"` to the french input, and vice-versa.

2024-05-02 14:42 UTC, andrewleith commented on app/templates/components/textbox.html
> +  field,
This should probably be pluralized, since we are passing multiple fields in and not just one.

2024-05-02 16:28 UTC, jzbahrai commented on app/main/views/email_branding.py
> +            alt_text_en=form.alt_text_en.data,
this change is here: https://github.com/cds-snc/notification-admin/pull/1824/files#diff-b838f01bb7b2e3334c72bd5389e18ffe44871f9cd3beefbb227303b00a97892c , as it needed the utils change, I will merge that PR into this PR

2024-05-02 16:28 UTC, jzbahrai commented on app/assets/javascripts/formValidateRequired.js
> +(function () {
all andrew

2024-05-02 17:54 UTC, amazingphilippe commented on app/templates/components/textbox.html
> +        {{ textbox(localized_field, localized_field.label.text, width='w-full', data_error_msg=localized_field.validators[0].message) }}
Would be nice to bake this in our form definitions. Are we always planning to display EN before FR? Or would we want the flexibility to also do FR before EN?

2024-05-02 18:13 UTC, amazingphilippe commented on app/templates/components/textbox.html
> +        {{ textbox(localized_field, localized_field.label.text, width='w-full', data_error_msg=localized_field.validators[0].message) }}
When we call localized_fields, we could pass in a dict, rather than an array: That way we can associate a lang key with the field.

2024-05-03 15:33 UTC, andrewleith commented
> This may be unrelated to this work, but when I try to update an existing branding to add en/fr alt text with `No organisation ` selected SQLAlchemy in API complains about the `organisation_id` being `-1`:
> 
> ```
> sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: "-1"
> LINE 1: ...E email_branding SET colour=NULL, organisation_id='-1', alt_...
>                                                              ^
> [SQL: UPDATE email_branding SET colour=%(colour)s, organisation_id=%(organisation_id)s, alt_text_en=%(alt_text_en)s, alt_text_fr=%(alt_text_fr)s WHERE email_branding.id = %(email_branding_id)s]
> [parameters: {'colour': None, 'organisation_id': '-1', 'alt_text_en': 'abc', 'alt_text_fr': 'bcb', 'email_branding_id': UUID('c90eff6c-fa2f-48f6-ac58-a589442b27ae')}]
> ```

Yeah I think this is an outstanding issue from our initial implementation.  We need to fix this!

2024-05-03 15:41 UTC, whabanks commented on app/main/views/email_branding.py
> +            alt_text_en=form.alt_text_en.data,
Still seems to be missing on L230 in `create_branding_request`. When I tried to request a new logo from the service settings page I got the same error about missing params.

I added these lines and it worked.
![image](https://github.com/cds-snc/notification-admin/assets/7444334/d15a9108-159e-4d98-a1d8-44af5c7f2548)

2024-05-06 13:06 UTC, jzbahrai commented
In regards to @andrewleith's comment, I made another PR: https://github.com/cds-snc/notification-admin/pull/1835

2024-05-06 13:35 UTC, whabanks approved these changes
LGTM!

2024-05-06 13:37 UTC, merged