Feat/add validation summary
cds-snc/notification-admin pull request #1823
Opened 2024-04-29 16:54 UTC by andrewleith

# Summary | Résumé

This PR adds a WTForms-based `validation_summary` macro to allow display of an accessible validation summary component that:
- focused the browser on the summary when its presented
- enumerates the errors on the form
- provides links to each error 

# Test instructions | Instructions pour tester la modification

- Go to the `/register` page
- Attempt to register without satisfying all of the form fields
- Ensure missing/incorrect fields are part of the summary
- Ensure you can click on each link in the summary and are brought to the corresponding field

2024-04-29 18:40 UTC, amazingphilippe commented
I noticed a bug while styling the summary: When an error message contains a list, it adds them in the summary and we lose the context of the problem :(
<img width="525" alt="image" src="https://github.com/cds-snc/notification-admin/assets/5230720/0f554eda-eaa9-4951-a405-14e26a454da9">

2024-04-30 11:04 UTC, andrewleith commented
> I noticed a bug while styling the summary: When an error message contains a list, it adds them in the summary and we lose the context of the problem :( <img alt="image" width="525" src="https://private-user-images.githubusercontent.com/5230720/326550002-0f554eda-eaa9-4951-a405-14e26a454da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzUxOTUsIm5iZiI6MTcxNDQ3NDg5NSwicGF0aCI6Ii81MjMwNzIwLzMyNjU1MDAwMi0wZjU1NGVkYS1lYWE5LTQ5NTEtYTQwNS0xNGUyNmE0NTRkYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMTEwMTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFiYzIyYjQ3MzdkOWU5NjhjYzEzZDVkYjYyZTdkYzBjYmM3ZDU3NjAyMmQzOTMxMzM2OTMwNWM4OTQzY2Q5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zxtV6L4RHESuPUTdiomHxSAJQQka28BG4LXtqMdJl98">

I'm sure I can fix that - how do you reproduce it with multiple errors like that?

2024-04-30 12:03 UTC, andrewleith commented
Oh nevermind I see - we stuffed a bunch of `<li>`'s into the error message. We actually aren't creating valid markup here in general :/

2024-04-30 19:37 UTC, amazingphilippe requested changes
Just found one more case where we might want to handle html a bit more carefully: 

<img width="667" alt="image" src="https://github.com/cds-snc/notification-admin/assets/5230720/5a5b8977-07b0-4a3b-a22c-c5e7d5eb02b2">

I wonder if we can use a filter to sanitize the html so that we get a plain text value to show. Or we edit this error message in particular so that it doesn't have a link in it. Contacting us should be straightforward enough to not provide a link there.

2024-05-01 12:30 UTC, andrewleith commented
> I wonder if we can use a filter to sanitize the html so that we get a plain text value to show. Or we edit this error message in particular so that it doesn't have a link in it. Contacting us should be straightforward enough to not provide a link there.

Hmm yeah I feel like we are not using the WTForms validation errors correctly by including HTML in them.  I would lean towards stopping to put complex HTML in the error messages.

2024-05-02 13:43 UTC, andrewleith commented on app/main/forms.py
> +                    "A password that is hard to guess contains:<ul class='list list-bullet'><li>Uppercase and lowercase letters.</li><li>Numbers and special characters.</li><li>Words separated by a s
Yeah that would certainly work better!  I can make that change, too!

2024-05-02 14:46 UTC, amazingphilippe commented on app/main/forms.py
> +                    "A password that is hard to guess contains: <ul class='list list-bullet'><li>Uppercase and lowercase letters.</li><li>Numbers and special characters.</li><li>Words separated by a
Don't forget to update this one too!

2024-05-02 15:03 UTC, amazingphilippe approved these changes
Looks good to me! Really awesome work. Can't wait to try it on other forms! ⭐

2024-05-02 16:27 UTC, merged