Initial TemplateCategory client
cds-snc/notification-admin pull request #1884
Opened 2024-07-02 16:15 UTC by whabanks

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

> **Note**: Are you adding a new page from GC Articles? Make sure you add the endpoint to the [WAF rules](https://github.com/cds-snc/notification-utils/tree/main/.github/actions/waffles#supporting-a-new-url-within-gcnotify).

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

> **Note**: Ajoutez vous une nouvelle page par Articles GC? Assurez vous d'ajouter le chemin dans les [règles WAF](https://github.com/cds-snc/notification-utils/tree/main/.github/actions/waffles#supporting-a-new-url-within-gcnotify).

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2024-07-08 18:22 UTC, andrewleith requested changes
Looks good overall.  One issue when trying to add a new category, and one cache issue when trying to update a category - both detailed below.

2024-07-08 18:22 UTC, andrewleith commented on app/notify_client/template_category_api_client.py
> +    def update_template_category(
When I update a TC, i see the changes reflected in the form.  However, when I go back to the list the changes are not there.  I think we need to also delete the `template_categories` for this to work as expected.

2024-07-08 18:22 UTC, andrewleith commented on tests/app/notify_client/test_template_category_api_client.py
> +def test_update_template_category(template_category_client, mocker):
Are we able to test that the cache is removed here?

2024-07-08 19:06 UTC, whabanks commented on app/notify_client/template_category_api_client.py
> +    def update_template_category(
Good catch, I added a delete on `template_categories` when we update. I also added it when creating a category - the list page was not updating correctly when adding a new category.

2024-07-08 19:17 UTC, andrewleith commented on app/notify_client/template_category_api_client.py
> +    def update_template_category(
Looks good - working now!

2024-07-09 16:38 UTC, andrewleith approved these changes

2024-07-09 17:07 UTC, merged