Update nav pill styles
cds-snc/notification-admin pull request #1971
Opened 2024-10-17 15:04 UTC by andrewleith

# Summary | Résumé

This PR updates the nav pill styles with the new design as part of the annual limits work.

## Before
![image](https://github.com/user-attachments/assets/cb0b2bfa-cb84-4175-b30c-380d03285186)

## After
![image](https://github.com/user-attachments/assets/afbe8834-8422-48b3-8dec-76716fa9d2e7)

# Test instructions | Instructions pour tester la modification

This component is used in the following screens:
- Job details delivery report (click on a job from the dashboard)
- Notifications report page (click on the number of notifications sent from the dashboard)
- Templates used page (click on "See all templates used" on the dashboard)
- Messages sent page (click on "See all messages sent" on the dashboard)

2024-10-17 15:33 UTC, whabanks approved these changes
LGTM! Functionality still intact on screen readers too.

2024-10-17 15:44 UTC, amazingphilippe requested changes
Suggested one tiny change!

2024-10-17 15:44 UTC, amazingphilippe commented on app/assets/stylesheets/tailwind/components/pill.css
>    .pill a,
In this block, I think we could remove `self-center` This will ensure that the 4 wide pills on small screens still look decent!
From this:
<img width="406" alt="Capture d’écran, le 2024-10-17 à 11 43 40" src="https://github.com/user-attachments/assets/a5648560-777c-4152-908e-3acd2bb3cd0e">


To this!
<img width="365" alt="Capture d’écran, le 2024-10-17 à 11 43 35" src="https://github.com/user-attachments/assets/ea895692-15e6-47f1-bd14-d6d0d0e5f95a">

2024-10-18 11:22 UTC, andrewleith commented on app/assets/stylesheets/tailwind/components/pill.css
>    .pill a,
Cool.  I noticed mobile was a bit wonky but figured it was an existing issue.  This is a nice fix.  We could consider stacking later maybe - but this works great for short text!

2024-10-18 13:29 UTC, amazingphilippe approved these changes

2024-10-18 16:39 UTC, merged