Limits for go-live form step 2
cds-snc/notification-admin pull request #1984
Opened 2024-10-31 19:49 UTC by amazingphilippe

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

> **Note**: Are you adding a new page from GC Articles? Make sure you add the endpoint to the [WAF rules](https://github.com/cds-snc/notification-utils/tree/main/.github/actions/waffles#supporting-a-new-url-within-gcnotify).

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

> **Note**: Ajoutez vous une nouvelle page par Articles GC? Assurez vous d'ajouter le chemin dans les [règles WAF](https://github.com/cds-snc/notification-utils/tree/main/.github/actions/waffles#supporting-a-new-url-within-gcnotify).

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2024-11-04 15:45 UTC, YedidaZalik requested changes
@amazingphilippe now that I can see how this appears in the interface, I agree that "How many" works!
I also realized that we could shorten the headings from 
"About emails you want to send" to "Email" and "About text messages you want to send" to "Text messages" 
I think that could reduce cognitive load. Is it too late to do that?

2024-11-04 15:55 UTC, amazingphilippe commented
> "About emails you want to send" to "Email" and "About text messages you want to send" to "Text messages"

I agree! Not too late. Good catch!

2024-11-05 13:13 UTC, andrewleith requested changes
Looks great overall.  A few comments about adding some tests due to the overall complexity of this particular form.

2024-11-05 13:13 UTC, andrewleith commented on app/main/forms.py
> +            print("DEBUG: Trigger condition not met, stopping validation chain")
Debug statements should be removed

2024-11-05 13:13 UTC, andrewleith commented on app/main/forms.py
> +            print("DEBUG: Trigger condition not met, skipping validation")
Debug statements should be removed

2024-11-05 13:13 UTC, andrewleith commented on app/main/forms.py
> +        _l("How many text messages do you expect to  send in a year?"),
There are some extra spaces in some of these strings.

2024-11-05 13:13 UTC, andrewleith commented on app/main/forms.py
Since this form is quite complex, it would be good to have some more tests around it.  Specifically, that the `OptionalIntegerRange` is working how you expect it to (for example, that validations only fire when the last radio is selected and no value is given, or the value is out of range, etc.)  

There only seems to be extra validation (and extra "other/specify" fields) on two of the four "how many" fields.  Is that intentional?

2024-11-05 13:13 UTC, andrewleith commented on app/main/forms.py
> +        ]
This validation doesn't trigger when you input the the min boundary.  I.e. where it says "More than 100 000`, you can enter exactly 100,000 and there is no validation error.

2024-11-05 15:15 UTC, amazingphilippe commented on app/main/forms.py
Absolutely, I'll work on some tests. 

And yes! The form only has 2 conditional fields total.

2024-11-05 18:29 UTC, amazingphilippe commented on app/main/forms.py
> +        ]
I've added +1 to the "min" to fix this. Which makes sense with how the attribute should work

2025-02-26 20:13 UTC, amazingphilippe commented on app/main/forms.py
> +class BaseGoLiveAboutNotificationsForm:
Made a "Base" GoLiveAboutNotificationsForm

2025-03-04 19:48 UTC, andrewleith approved these changes
LGTM

2025-03-04 20:16 UTC, merged