Fix content on the email address settings page
cds-snc/notification-admin pull request #1988
Opened 2024-11-04 20:09 UTC by amazingphilippe

# Summary | Résumé

After changing the creat a service flow, we must've forgottent to check the contents of the settings page where one can change a service sending email address. 

this PR updates the content of that page, so that it matches other changes we did, and most importantly fixes a missing translation. 

# Test instructions | Instructions pour tester la modification

1. In any service
2. In the settings
3. Click on the sending email address settings
4. You should be on "Change your sending email address"
5. Toggle to FR and make sure there is no English content
6. Test the live preview functionality
7. Save the form and check that the value was saved properly.

2024-11-04 20:09 UTC, amazingphilippe commented on app/config.py
Auto formatting...

2024-11-05 12:43 UTC, andrewleith requested changes
Thanks for cleaning this up.  Looks like there is just a small issue with a line break that is breaking one translation, see below.

2024-11-05 12:43 UTC, andrewleith commented on app/templates/views/service-settings/email_from.html
> +      as possible.') }}</p>
There is a line break here breaking the translation.

2024-11-05 12:43 UTC, andrewleith commented on app/templates/views/service-settings/email_from.html
> +      as possible.') }}</p>
```suggestion
    <p>{{ _('Your sending email address helps build trust with recipients. A good email address is relevant and as concise as possible.') }}</p>
```

2024-11-05 15:11 UTC, amazingphilippe commented on app/templates/views/service-settings/email_from.html
> +      as possible.') }}</p>
Ah yes I see that now... For some reason format-on-save really wanted to break this line... I'll just accept your change here!

2024-11-07 14:51 UTC, andrewleith approved these changes
LGTM!

2024-11-13 15:11 UTC, merged