Fix the translations
cds-snc/notification-admin pull request #2020
Opened 2024-12-13 15:25 UTC by jzbahrai

# Summary | Résumé

Add missing translations

2024-12-13 18:55 UTC, andrewleith requested changes
Still missing one message:
![image](https://github.com/user-attachments/assets/0386496d-998a-4f04-9e97-7a6dc0f3d291)

2024-12-17 12:37 UTC, andrewleith commented
I fixed one string that didn't quite match the translation, as well as the some syntax that was preventing `pybabel` from detecting the missing translations.  Instead of :
`_('translation {'}.format(abc))` it should be `_('translation {'}').format(abc)`

@amazingphilippe , are there translations for these strings?  I couldn't find them in figma!

- `For more information, visit the <a href={}>usage report for {}</a>.`
- `<strong>{}</strong> cannot send any more {} until <strong>April 1, {}</strong>`
- `To send some of these messages now, edit the spreadsheet to <strong>{}</strong> recipients maximum. `

2024-12-17 20:04 UTC, amazingphilippe requested changes
We were missing translations in Figma as well:

```csv
"{} cannot send any more {} until April 1, {}","{} ne peut plus envoyer de courriels d’ici le 1<sup>er</sup> avril {}."
"For more information, visit the <a href={}>usage reports</a>.","Pour plus de détails, <a href={}>consulter les rapports d’utilisation</a>."
```
A few notes:
- removed `<strong>`.
- added a `<sup>` for properly formatting "1er" in FR
- removed link text customization with the service name. Less tricky in FR. The service name is also in the sentence before. 

Noticed 2 more things:
- We nest p tags (we shouldn't)
- We use the same font size for both paragraphs. Adding a class `text-title` to the first sentence in each condition would fix that.

2024-12-18 18:58 UTC, amazingphilippe requested changes
Suggested some changes. Though I haven't run these and they seem like a lot to suggest in a review...

2024-12-18 18:58 UTC, amazingphilippe commented on app/templates/partials/check/too-many-messages-annual.html
> +<div data-testid="exceeds-annual" class="text-title">
```suggestion
<div data-testid="exceeds-annual">
```

2024-12-18 18:58 UTC, amazingphilippe commented on app/templates/partials/check/too-many-messages-annual.html
> +      <p>{{ _('<strong>{}</strong> can only send <strong>{}</strong> more {} until annual limit resets').format(current_service.name, recipients_remaining_messages, units) }}</p>
```suggestion
      <p class="text-title">{{ _('<strong>{}</strong> can only send <strong>{}</strong> more {} until annual limit resets').format(current_service.name, recipients_remaining_messages, units) }}</p>
```

2024-12-18 18:58 UTC, amazingphilippe commented on app/templates/partials/check/too-many-messages-annual.html
> +      <p>{{ _('<strong>{}</strong> cannot send any more {} until <strong>April 1, {}</strong>').format(current_service.name, units, now().year) }}</p>
```suggestion
      <p class="text-title">{{ _('{} cannot send any more {} until April 1, {}').format(current_service.name, units, now().year) }}</p>
```

2024-12-18 18:58 UTC, amazingphilippe commented on app/translations/csv/fr.csv
> +"<strong>{}</strong> cannot send any more {} until <strong>April 1, {}</strong>","FR: <strong>{}</strong> cannot send any more {} until <strong>April 1, {}</strong>"
```suggestion
"For more information, visit <a href={}>usage reports</a>.","Pour plus de détails, <a href={}>consulter les rapports d’utilisation</a>."
"{} cannot send any more {} until April 1, {}","{} ne peut plus envoyer de {} d’ici le 1<sup>er</sup> avril {}."
```

2024-12-18 18:58 UTC, amazingphilippe commented on app/templates/partials/check/too-many-messages-annual.html
> +      <p>{{ _('For more information, visit the <a href={}>usage report for {}</a>.').format(url_for('.monthly', service_id=current_service.id), current_service.name) }}</p>
```suggestion
      <p>{{ _('For more information, visit <a href={}>usage reports</a>.').format(url_for('.monthly', service_id=current_service.id)) }}</p>
```

2024-12-19 13:55 UTC, andrewleith commented on app/translations/csv/fr.csv
> +"<strong>{}</strong> cannot send any more {} until <strong>April 1, {}</strong>","FR: <strong>{}</strong> cannot send any more {} until <strong>April 1, {}</strong>"
No prob..
FYI, I added the strong tags originally to highlight the most important infomation, because these error messages are so long they seemed hard to parse.

2025-01-06 15:56 UTC, whabanks approved these changes
Tested locally, LGTM!

Not enough for full job send:
![image](https://github.com/user-attachments/assets/c7083b47-dca7-4823-9dab-fbb89d7118dd)

Service settings:
![image](https://github.com/user-attachments/assets/aa107824-f250-49b4-a0f4-ab1fa7616fc8)

Send while at the limit:
![image](https://github.com/user-attachments/assets/e178cc73-dbbb-4813-b024-e49b8fa78754)

2025-01-06 18:45 UTC, merged