Admin missing translations and tiny improvements.
cds-snc/notification-admin pull request #2023
Opened 2024-12-20 19:04 UTC by amazingphilippe

# Summary | Résumé

This addresses https://github.com/cds-snc/notification-planning/issues/998

- Adds or calls translation keys where missing
- Adds translations where missing
- Some style tweaks on the live service table to improve readability. 

---

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2024-12-20 19:29 UTC, amazingphilippe commented on app/templates/components/empty-list.html
> +  class="flex items-center border-dashed border-1 border-gray-400 p-8 sm:bg-{{img}} sm:bg-right bg-empty-state min-h-emptyState"
I've only added a min-height. The rest is auto formatting.

2024-12-20 19:30 UTC, amazingphilippe commented on app/templates/components/table.html
> +          {{ empty_list(heading=empty_message) }}
Why not use the empty component!

2024-12-20 19:30 UTC, amazingphilippe commented on app/templates/components/table.html
> +<th class="table-field {{ cell_width if cell_width}}" scope="row" rowspan="{{ rowspan }}">
This lets us create `<th>` that span many rows, like we have on the admin panel for each service usage.

2024-12-20 19:33 UTC, amazingphilippe commented on app/templates/partials/nav/gc_header_nav.html
> +
This fixes the empty main navigation in platform admin. ✨ No more layout shift ✨ 🎉

2024-12-20 19:33 UTC, amazingphilippe commented on app/templates/partials/nav/gc_header_nav.html
> +                is_active=header_navigation) }}
Just adding the aria-current

2025-01-02 15:43 UTC, amazingphilippe commented on app/templates/views/organisations/organisation/index.html
> +      <a href="{{ url_for('main.service_dashboard', service_id=service.id) }}" class="browse-list-link">{{ service['name']
Found out that there is not `sid/usage` page. Staging and prod fall back to dashboard somehow, so I've changed it to actually be the dashboard. (And fixed the tests)

2025-01-08 20:27 UTC, smcmurtry requested changes
I haven't noticed any issues with the translations you've added - they look great! 

Could you split this PR into a few different ones so that we can merge it in piece by piece?

2025-01-08 20:27 UTC, smcmurtry commented on app/templates/partials/nav/gc_header_nav.html
> +
Could you move this change into its own PR? So we can make this PR just translation changes?

2025-01-08 20:27 UTC, smcmurtry commented on app/templates/components/table.html
> +          {{ empty_list(heading=empty_message) }}
Could you move this change into its own PR? Along with the change to the empty_list component.

2025-01-08 20:27 UTC, smcmurtry commented on app/templates/partials/nav/gc_header_nav.html
> +                is_active=header_navigation) }}
When I log in, I now see the blue underline under 2 menu items which seems wrong: 
![Screenshot 2025-01-08 at 3 18 59 PM](https://github.com/user-attachments/assets/71464585-c15f-402c-86c7-ada48f6fa159)

Could you move this change out of this PR so we can make this one just translations?

2025-01-09 19:10 UTC, amazingphilippe commented on app/assets/stylesheets/index.css
Probably due to the rebuild after I reverted the changes.

2025-01-09 20:36 UTC, merged