Port button styles to tailwind
cds-snc/notification-admin pull request #786
Opened 2020-10-09 19:02 UTC by brdunfield

This PR removes `_buttons.scss` and ports its styles into tailwind.

There is also some tailwind file structure renaming / cleanup.

[WIP]:
- Mobile buttons are not yet correct
- Need to remove / port the styles in `app/assets/stylesheets/toolkit/design-patterns/_buttons.scss`

2020-10-09 19:03 UTC, brdunfield commented on app/assets/stylesheets/tailwind/layout.css
> -  .container {
This style was not actually being used because importing other files was broken. .container is a base tailwind util class.

2020-10-09 19:03 UTC, brdunfield commented on app/assets/stylesheets/tailwind/tailwind.css
> +@tailwind base;
Moved these imports into its own file to preserve code order

2020-10-09 19:04 UTC, brdunfield commented on package.json
> +    "postcss-import": "^12.0.1",
This was needed to allow other css files to actually be imported in style.css

2020-10-15 15:26 UTC, AntoineAugusti requested changes
Thanks for you great work tracking down all these buttons in the codebase! A few suggestions and comments.

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/javascripts/apiKey.js
> +        <input type='button' class='api-key-button-show button-secondary' value='${window.polyglot.t('show')} ${thing}' />
It seems like `api-key-button-copy` and `api-key-button-show` are classes used by JS to perform an action.

In the past I named these classes only used by JS like `js-class-name` to point that deleting them has an impact on features and not on the UI. What do you think of this? Would you like to make these changes as you go?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/javascripts/fileUpload.js
> +    this.showCancelButton = () => $('#file-upload-button', this.$form).replaceWith(`
Same remark about `js-` prefix

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +    padding: .526315em .789473em .263157em;
Can you replace this with Tailwind padding classes?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +    background-color: theme("colors.green.default");
Any reason to write this instead of `bg-green`?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +    background-color: theme("colors.blue.lighter");
`bg-blue-lighter`?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +    background-color: theme("colors.green.hover");
`hover:bg-green-hover`?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +  }
Delete and use utility classes on these buttons? Unsure if we want to have helper classes/embrace utilities only/have templates we include

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +  }
Same question than `.button-red`

2020-10-15 15:26 UTC, AntoineAugusti commented on tailwind.config.js
> +        border: "#b5babe"
Do you know if we can reduce the number of gray shades?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +  /* Note: Buttons are <a> sometimes, which is why :link and : visted styles exist */
```suggestion
  /* Note: Buttons are <a> sometimes, which is why :link and : visited styles exist */
```

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +  }
If this button appears only once, can we put all these utilities in the HTML directly?

2020-10-15 15:26 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +@layer components {
I think we've got a mix of `.button` and `.btn`, could we keep only 1 value?

2020-10-15 15:35 UTC, brdunfield commented on app/assets/stylesheets/tailwind/buttons.css
> +  }
This might be a good point to involve design. I know a big concern was having to change a bunch of files to make a small style change. In this case, if we wanted to style a red button differently, we would only need to make changes here.

I know tailwind's core concept is ultility class first, but these helper classes are available for scalability. So.. it's not a clearly defined answer here. :(

2020-10-15 15:38 UTC, brdunfield commented on tailwind.config.js
> +        border: "#b5babe"
It looks like default is not in use. I could make "button" the default and cut this down by one.

2020-10-15 15:39 UTC, brdunfield commented on app/assets/stylesheets/tailwind/buttons.css
> +@layer components {
Agreed - this is an artifact of the old and new conventions co-existing before this that I must have missed.

2020-10-15 15:41 UTC, brdunfield commented on app/assets/stylesheets/tailwind/buttons.css
> +    padding: .526315em .789473em .263157em;
None of the tailwind padding classes correspond to exactly these values - we could consult with design and see if the closest ones are acceptable.

2020-10-15 16:47 UTC, brdunfield commented on app/assets/javascripts/apiKey.js
> +        <input type='button' class='api-key-button-show button-secondary' value='${window.polyglot.t('show')} ${thing}' />
I would need more context around this. I didn't modify the api-key classes here.

2020-10-15 16:55 UTC, brdunfield commented on app/assets/stylesheets/tailwind/buttons.css
> +  }
This button comes from the main page_footer template, which is used in various places, not just here.

2020-10-15 16:58 UTC, brdunfield commented on tailwind.config.js
> +        border: "#b5babe"
Removed "button" and made it "default"

2020-10-15 19:41 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +    padding: .526315em .789473em .263157em;
Awesome sounds like a good plan! Migrate CSS files and then update them after consulting with design.

2020-10-15 19:41 UTC, AntoineAugusti commented on app/assets/javascripts/apiKey.js
> +        <input type='button' class='api-key-button-show button-secondary' value='${window.polyglot.t('show')} ${thing}' />
It was a proposal to start to prefix classes only used by JavaScript with `js-` to make them pop in the HTML code. It conveys a warning: "attention, I'm not used for UI purposes but for feature purposes"

2020-10-15 19:41 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +    background-color: theme("colors.green.default");
My comment was about writing `@apply bg-green` instead of this line of code. They both do the same, agreed.

2020-10-15 19:41 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/buttons.css
> +  }
Yeah, it's a team preference. If we maintain a low number of these classes, a minimum amount of CSS files, it seems a good idea.

2020-10-15 19:44 UTC, AntoineAugusti commented on app/templates/components/page-footer.html
> +        class="button text-base outline-none focus:shadow-outline {% if destructive %}-destructive{% endif %}"
I think the CSS class `-destructive` doesn't exist anymore. You may want to remove this from the HTML or convert to utility classes

2020-10-15 19:47 UTC, brdunfield commented on app/templates/components/page-footer.html
> +        class="button text-base outline-none focus:shadow-outline {% if destructive %}-destructive{% endif %}"
Good catch - i've updated it to at the "button-red" class when destructive

2020-10-15 20:04 UTC, brdunfield commented on tailwind.config.js
> +        border: "#b5babe"
Turns out the default grey actually was in use on the homepage. I'm going to revert this change.

I think any discussion around actually reducing the colour palette will be a design conversation and will take effect withe the new styles.

2020-10-15 22:02 UTC, AntoineAugusti approved these changes
Awesome! :shipit:

2020-10-16 12:49 UTC, merged