Add security.txt for Vulnerability Disclosure Practices
cds-snc/notification-admin pull request #831
Opened 2020-11-25 17:09 UTC by RenDavidDimen

#### Overview
Adding security.txt route for Vulnerability Disclosure Practices. Information on page generated by filling out the security form on [securitytxt.org](https://securitytxt.org/)

#### Addresses
https://trello.com/c/F7wzxTz3/110-create-a-securitytxt-file-for-vulnerability-disclosure-practices
https://github.com/cds-snc/notification-api/issues/1148

2020-11-25 17:55 UTC, AntoineAugusti requested changes
Good work, thanks!

A few suggestions

2020-11-25 17:55 UTC, AntoineAugusti commented on app/main/views/index.py
> +        'Contact: mailto:security@cds-snc.ca\n'
```suggestion
        'Contact: mailto:securite@cds-snc.ca\n'
```
The email address is different in French

2020-11-25 17:55 UTC, AntoineAugusti commented on app/main/views/index.py
> +        'Policy: https://github.com/cds-snc/.github/blob/master/SECURITY.md\n'
Could you link to the security page instead?

2020-11-25 17:55 UTC, AntoineAugusti commented on app/main/views/index.py
> +def security_txt():
Could you have a list and then `'\n'.join(list)` instead?

2020-11-25 17:55 UTC, AntoineAugusti commented on tests/app/main/views/test_index.py
> +    assert url_for('main.security_txt') == '/.well-known/security.txt'
That's a good thing to verify!

2020-11-25 18:05 UTC, RenDavidDimen commented on app/main/views/index.py
> +        'Contact: mailto:security@cds-snc.ca\n'
Good catch, I'll fix that now 👍

2020-11-25 18:12 UTC, RenDavidDimen commented on app/main/views/index.py
> +        'Contact: mailto:security@cds-snc.ca\n'
Fix should be in place now

2020-11-25 18:13 UTC, RenDavidDimen commented on app/main/views/index.py
> +        'Policy: https://github.com/cds-snc/.github/blob/master/SECURITY.md\n'
That's a good idea, I'll switch this out for the security page link

2020-11-25 18:15 UTC, RenDavidDimen commented on app/main/views/index.py
> +def security_txt():
Yes, I don't see why not. It might be better to do it that way as well should this information need some updating. (It could also help in avoiding some minor syntax errors)

2020-11-25 19:28 UTC, RenDavidDimen commented on app/main/views/index.py
> +        'Policy: https://github.com/cds-snc/.github/blob/master/SECURITY.md\n'
I've switched the URL. For future reference, once notify is out of alpha, I believe this reference will need to be updated.

2020-11-25 22:13 UTC, RenDavidDimen commented on tests/app/main/views/test_index.py
> +        '\n'.join(security_info)
I'm curious if anyone has any qualms with how this test is currently set up. My view is that it is prepping the data the same way it is being done in `index.py`. Should we write tests asserting the result to be the literal expected value or is setting them up in the same way fine?

2020-11-26 15:23 UTC, AntoineAugusti commented on tests/app/main/views/test_index.py
> +        '\n'.join(security_info)
I'm not sure you need to make sure that the exact content is the same. As you say, you're recreating the logic. You can test maybe a specific important line, maybe `Contact: mailto:security@cds-snc.ca`

2020-11-26 16:16 UTC, RenDavidDimen commented on tests/app/main/views/test_index.py
> +        '\n'.join(security_info)
That makes sense. I think that since we're following `security.org`'s file standard, I may leave them in for these tests to ensure that the format is the same.

2020-11-26 16:19 UTC, brdunfield commented on app/main/views/index.py
> +        'Contact: mailto:security@cds-snc.ca\n'
Do we actually have a french security email as well? I don't see it anywhere obvious.

2020-11-26 16:20 UTC, brdunfield commented on app/main/views/index.py
> +        'Contact: mailto:security@cds-snc.ca\n'
Oh it's in this PR

2020-11-26 21:32 UTC, RenDavidDimen commented on app/main/views/index.py
> +        'Contact: mailto:security@cds-snc.ca\n'
Created a config variable to store the `security-securite@cds-snc.ca` email

2020-11-26 21:57 UTC, AntoineAugusti requested changes
Nice, thanks for adding a config!

Could you use the new config in the `/security` page as well?

2020-11-26 21:57 UTC, AntoineAugusti commented on app/main/views/index.py
> +        'Contact: mailto:' + current_app.config["SECURITY_EMAIL"],
```suggestion
        f'Contact: mailto:{current_app.config["SECURITY_EMAIL"]}',
```

If you like f-strings, you can use this syntax. Really not important, just a suggestion

2020-11-27 20:12 UTC, RenDavidDimen commented on app/main/views/index.py
> +        'Contact: mailto:' + current_app.config["SECURITY_EMAIL"],
Read a little more into using f-strings and it seems the consensus is that it tends to be more read-able. As someone who likes to understand what they read, I'll be switching to using f-strings here!

2020-11-27 20:56 UTC, AntoineAugusti requested changes

2020-11-27 20:56 UTC, AntoineAugusti commented on app/main/views/index.py
> +        'Policy: https://notification.alpha.canada.ca/security',
You should `url_for('main.security', _external=True)` here to avoid having the alpha domain hardcoded here

2020-11-30 14:52 UTC, AntoineAugusti approved these changes
Looks perfect to me! Good to go 🚢

2020-11-30 15:07 UTC, merged