Add Functionality to Send New Registered User Data to Freshdesk
cds-snc/notification-admin pull request #844
Opened 2020-12-07 14:44 UTC by RenDavidDimen

Upon a successful registration, a new user will have their email, name, and date/time of sign up to Freshdesk

Requires [changes made for the same ticket](https://github.com/cds-snc/notification-api/pull/1188) in the notification-api repo.

2020-12-10 15:07 UTC, RenDavidDimen commented on tests/app/main/views/organisations/test_organisation_invites.py
> +    mocker.patch('app.user_api_client.send_new_registration_data')
I'm mocking the API call in these tests as they appear to be hitting the `"main.verify"` route. I had originally attempted to put this code in the `conftest.py` file and reference the mock accordingly but that appears to give me 403 response statuses. I've attempted to explicitly import the mock definition to have the same 403 errors occur.

I'm currently looking at the parameters passed to the mocking functions in `conftest.py` as a potential culprit to the 403 errors

2020-12-14 15:24 UTC, RenDavidDimen commented on tests/app/main/views/organisations/test_organisation_invites.py
> +    mocker.patch('app.user_api_client.send_new_registration_data')
I couldn't seem to find the reason why centralizing the test in `conftest.py` caused some tests to throw. If anyone might have a better solution, I'm open to suggestions 🙂

2020-12-14 17:02 UTC, AntoineAugusti requested changes

2020-12-14 17:02 UTC, AntoineAugusti commented on app/notify_client/user_api_client.py
> +        data = {'id': self.notify_user_id, 'name': name, 'email': email, 'date': date}
You need to build a `message` here or on the API side

2021-03-02 20:20 UTC, AntoineAugusti commented
Closing this stale PR, we reworked our Freshdesk integration in https://github.com/cds-snc/notification-api/pull/1222

2021-03-04 14:53 UTC, closed without merging