Small content/copy changes
cds-snc/notification-admin pull request #855
Opened 2020-12-17 18:36 UTC by anikbrazeau

Fixing blatant errors/inconsistencies found in content audit for accuracy and consistency
- Use "mobile" rather than "cellular"
- Use "retirer" for "remove" in French
- Use "interrompre" for "suspend" in French
- Specify what "All" refers to in French "Tous les gabarits"
- Tweak error message for empty state
- Fix grammar and capitalization

2020-12-17 18:39 UTC, anikbrazeau commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix blatant content errors/inconsistencies from audit](https://trello.com/c/ILdR7wMG/139-fix-blatant-content-errors-inconsistencies-from-audit)

2020-12-17 23:40 UTC, jimleroyer commented on app/translations/csv/en.csv
> +"contact us","nous joindre"
Do you know what happens if the French version is present in that file? They're usually all empty in `en.csv`.

2020-12-17 23:45 UTC, jimleroyer commented on app/translations/csv/fr.csv
> +"All","Tout les gabarits"
Probablement _Tous les gabarits_,  le pronom se conjuguant maintenant avec les mots qui suivent.

2020-12-17 23:46 UTC, jimleroyer commented on app/translations/csv/fr.csv
> +"is ready to use","est prête à utiliser"
Difficile à dire ici en manquant le contexte. 🤔

2020-12-17 23:46 UTC, jimleroyer commented on app/templates/partials/messages-status-fr.html
> +      Dans un tel cas, le fournisseur n’a pas pu livrer le message puisque l’adresse courriel ou le numéro de téléphone était erroné. Vous devriez supprimer ce destinataire de votre base de données.
Super 💥

2020-12-17 23:48 UTC, jimleroyer commented
Merci d'améliorer le français de la plateforme. Il n'y a qu'un commentaire où je me questionne sur la conjugaison.

2020-12-18 07:22 UTC, AntoineAugusti requested changes

2020-12-18 07:22 UTC, AntoineAugusti commented on app/translations/csv/fr.csv
> +"We’ll email you once your branding’s ready to use, or if we need any more information.","Nous vous enverrons un courriel dès que votre image de marque sera prête à être utiliser, ou bien si nous avo
```suggestion
"We’ll email you once your branding’s ready to use, or if we need any more information.","Nous vous enverrons un courriel dès que votre image de marque sera prête à être utilisée, ou bien si nous avons besoin de plus d'informations."
```

2020-12-18 07:22 UTC, AntoineAugusti commented on app/translations/csv/en.csv
> +"contact us","nous joindre"
This string was meant to be in the `fr.csv` file I think

2020-12-18 13:25 UTC, anikbrazeau commented on app/translations/csv/fr.csv
> +"is ready to use","est prête à utiliser"
Je pense que le contexte peut varier (soit une adresse courriel _accord féminin_ ou un numéro de téléphone _accord masculin_) ex: 
![image](https://user-images.githubusercontent.com/38330843/102619480-8910f380-410a-11eb-919e-e61709135cd7.png)

2020-12-18 13:26 UTC, anikbrazeau commented on app/translations/csv/en.csv
> +"contact us","nous joindre"
MERCI 😅 good catch

2020-12-18 14:36 UTC, AntoineAugusti approved these changes

2020-12-18 15:13 UTC, merged