Create 'Why GC Notify' page content
cds-snc/notification-admin pull request #866
Opened 2020-12-30 22:13 UTC by anikbrazeau

# Summary

Create new page for Why GC Notify (ahead of Beta) with available English and French content. Having this page will be useful to link to in marketing to decision makers who have questions about whether it meets all the GoC requirements.

This page includes information that :
- shows how GC Notify meets GC requirements and standards
- help people advocate for it more confidently
- highlights official languages (bilingual)
- federal identity program compliance
- privacy, public data protection
- security and reliability
- no approvals needed
- no procurement (free)
- cloud and digital standards

Figma reference: https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Features-Compliance-Fonctionnalit%C3%A9s-Conformit%C3%A9?node-id=514%3A3

This will eventually need to have tests added and be added to global navigation when that change is made. It would also be nice to add checkmark styling as shown in Figma.

2021-01-06 00:40 UTC, jimleroyer commented on app/assets/stylesheets/tailwind/style.css
> +}
This is a CSS based checkmark. I didn't add it to the HTML yet but I can try tomorrow; this requires a bit more CSS tailwind machinery to correctly align it as showed in the figma diagram. The following screenshot shows the broken version:
![image](https://user-images.githubusercontent.com/805567/103715110-c7713400-4f8d-11eb-802b-3adf41ac57c7.png)

2021-01-06 00:42 UTC, jimleroyer commented on app/templates/views/signedout.html
> +            alt="An illustration of a laptop with a message window on the screen and a cellphone with a message and a callout blurb."
I removed the extra curly and round braces. It seems like a typo for a potential translation of the alt image text.

2021-01-06 00:51 UTC, jimleroyer commented on app/assets/stylesheets/tailwind/style.css
> +}
I realized though that if we support IE 11, we should use an image, because it does not support much in terms of CSS rotate transformation. 😢 

https://caniuse.com/?search=rotate

2021-01-07 01:01 UTC, jimleroyer commented on app/assets/stylesheets/tailwind/style.css
> +}
In the end, I reused the existing `tick.png` image which is what I was searching for in a checkmark.

2021-01-07 01:07 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
I would prefer to have the style declared as a class in our CSS files. I will look what I can do tomorrow morning but I am opened to suggestion on proper practice in the project.

2021-01-07 13:25 UTC, AntoineAugusti requested changes
Can you not commit the following files as they are not related to changes?
- app/assets/javascripts/main.min.js
- package-lock.json

If you're changing Tailwind styles, you can run `npm run tailwind` and do not commit an updated version of the main.min.js file. I think @brdunfield said that it currently is broken and we need to take a look.

Made some commits about responsive and content as well

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <p><a href="{{ url_for('main.security') }}">{{ _('Learn more about security') }}</a>.
```suggestion
  <p><a href="{{ url_for('main.security') }}">{{ _('Learn more about security') }}</a>
```
No final dot in Figma and to be consistent with other links

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
You should use `{{ asset_url('images/tick.png') }}` (top of my head, may want to check elsewhere)

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +{% from "components/table.html" import mapping_table, row, text_field, edit_field, field with context %}
Clean up unused imports

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +<div class="pl-24">
The page is currently not responsive, ticks are outside of the viewport on mobiles.

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
My understanding is that we don't any limits for emails and we have a variable limit for SMS. Could you check this information and use a variable? We have `DEFAULT_FREE_SMS_FRAGMENT_LIMITS` in config.py, would be a good thing to update it there as well 👌

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
Integers can be formatted in French/English with `| format_number`

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +            alt="An illustration of a laptop with a message window on the screen and a cellphone with a message and a callout blurb."
The alt text shouldn't be in English only

2021-01-07 13:25 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
You should be able to use utility classes for that without declaring a new CSS class.

Take a look at:
https://tailwindcss.com/docs/height
https://tailwindcss.com/docs/width
https://tailwindcss.com/docs/margin

2021-01-07 13:31 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
For these icons, you should add `aria-hidden="true"` to say that these images do not convey meaningful information and are just decorative

2021-01-07 15:00 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
It's true, but I was thinking more of a single class regrouping these properties in the `style` attribute, or a reusable component.

2021-01-07 15:05 UTC, jimleroyer commented
> Finally, I've seen that the Figma file has some unique icons per section, could you use these instead of the generic tick every time?

I don't understand what you mean. There is one green checkmark for all of the subtitles. Can you rephrase?

2021-01-07 15:06 UTC, AntoineAugusti commented
@jimleroyer The [Figma file](https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Features-%2B-Compliance-%7C-Fonctionnalit%C3%A9s-%2B-Conformit%C3%A9?node-id=514%3A3) has multiple screens, 2 for English (not sure why). The bottom one has various icons and I like this version 🎨

2021-01-07 15:07 UTC, AntoineAugusti commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
If this is only used in this page, the Tailwind way would be to duplicate a bunch of utility classes in the `class` attribute of these images

2021-01-07 15:13 UTC, jimleroyer commented
@AntoineAugusti Can you post a screenshot of what you see on Figma? I see one page for each English and French version and they all have the green checkmark.

2021-01-07 21:38 UTC, jimleroyer commented on app/templates/views/signedout.html
> +            alt="An illustration of a laptop with a message window on the screen and a cellphone with a message and a callout blurb."
Absolutely.. there are 23 instances of `alt` text that are not localized. Is that okay if I open a new ticket for this?

2021-01-07 21:42 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +            alt="An illustration of a laptop with a message window on the screen and a cellphone with a message and a callout blurb."
Sure, this is not blocking for this PR if this is not a one time thing 👍

2021-01-07 21:44 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +<div class="pl-24">
Hmm I tested it with iphone 6 resolution and it seems to work:

Can you share with me what is not working? or a screenshot on your end of what you have?

A screenshot of what I have, not with the ticks but the new icons:

![Why-use-GC-Notify-–-Notify--mobile](https://user-images.githubusercontent.com/805567/103948293-89981b00-5107-11eb-9195-bb277bc638f9.png)

2021-01-07 21:48 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <img src="/static/images/tick.png" class="float-left" style="width: 4rem; height: 4rem; margin-left:-5rem;"/>
One thing we could do is to put these sections into a macro, like what [tailwind documentation recommends](https://tailwindcss.com/docs/extracting-components) but with using *vue.js*. Maybe it isn't enough for now though.

2021-01-07 22:09 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
I see we have `DEFAULT_SERVICE_LIMIT` defined like this on service creation:

```
service_id = service_api_client.create_service(
            service_name=service_name,
            organisation_type=organisation_type,
            message_limit=current_app.config['DEFAULT_SERVICE_LIMIT'],
            restricted=True,
            user_id=session['user_id'],
            email_from=email_from,
            default_branding_is_french=default_branding_is_french,
        )
```

Is this okay to assume that this would be a limit on emails? I will make changes as this is the case for now and remove it if not.

2021-01-07 23:21 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
Actually, forget about it, it does not make sense as the config variable is set to `50` (and it's way too low obviously).

2021-01-07 23:24 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
Let's talk tomorrow on Slack about this.

2021-01-08 16:35 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
Regarding the limit on messages: I spoke to Bryan and he confirms that 10 million emails per service per year would be the limit. After limit would be reached, a MOU would need to be agreed upon with the service that gets out of this limit. It does not seem like there is any hard limit coded in though, but the text description would be valid per our business rules.

2021-01-08 17:09 UTC, jimleroyer commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
@anikbrazeau @AntoineAugusti @willeybryan @ClementineHahn For reference here ^^^^ we should probably concert on the email limit per year.

2021-01-08 17:23 UTC, willeybryan commented on app/templates/views/why-notify.html
> +  <p>{{ _('GC Notify is a government-run service, using it does not require any external procurement. You can send up to 10 million emails and 10,000 text messages per year for free for each of your
We have a draft MOU that Policy is helping with. We don't have anyone on an MOU right now, we just want to have one available. The limits per year are business limits and are not hard limits. We will make exceptions. 

The 10 Million email one was picked because at a cost of $1000 USD we want to negotiate an MOU with that departments. For SMS We picked 10,000 because of the unknown factors, such as international SMS potentially causing large cost surprises. 

These limits are just for when we need to start thinking about collecting $$$ in the form of cost recovery. We can control system limits differently. 

We aren't doing any cost recovery right now, and we may not for a while, but this will help set expectations for department on when that kicks in. 

We may want to put in more info explaining that More is available it's just gonna need cost recovery.

2021-01-08 17:36 UTC, anikbrazeau commented on app/templates/views/signedout.html
> +            alt="An illustration of a laptop with a message window on the screen and a cellphone with a message and a callout blurb."
😅 happy to help fill in those alt text gaps! do you have a link to that new ticket?

2021-01-08 18:43 UTC, jimleroyer commented on app/templates/views/signedout.html
> +            alt="An illustration of a laptop with a message window on the screen and a cellphone with a message and a callout blurb."
Just created an issue in the parking lot column: https://trello.com/c/ByGjBswg/300-translate-alternative-text-on-images-in-the-signed-out-view-for-accessibility

After more careful look, the issue is that we have 1 instance of a text that is not translated and numerous instances of hardcoded translation values using `if... else... endif` conditions instead of our newer CSV translation mechanism.

2021-01-08 19:21 UTC, AntoineAugusti approved these changes
Great work @anikbrazeau @jimleroyer and the design team.

Good to go 🚢 

@jimleroyer, you'll new to merge in the `master` branch. You may need to run `npm run tailwind` one last time, don't include the `main.min.js` file in your changes. This is required because https://github.com/cds-snc/notification-admin/pull/865 just landed on the other branch

2021-01-08 21:43 UTC, merged