Homepage content update
cds-snc/notification-admin pull request #894
Opened 2021-01-27 15:04 UTC by RenDavidDimen

# Summary | Résumé

Content update for homepage strings, its content, section ordering, and image references. Static image files are uploaded to the Staging S3 bucket, will need to upload them to S3 Production should the review be successful

Trello Card: https://trello.com/c/gEGgx51w/204-update-homepage-content

2021-01-27 15:52 UTC, AntoineAugusti requested changes
Good work! A few suggestions. I'll let you fix the footer colour as well to see links.

Can #864 be closed in favour of this one?

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +  <div class="bg-blue" role="main">
I think the blue colour `backgr` was introduced just for this page. Can you double-check it's not used anymore and then delete it here?

https://github.com/cds-snc/notification-admin/blob/c920b0968e221044e7c57bf6387e7a4e033d6344/tailwind.config.js#L57

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +              {{ _("Personalise your messages, while protecting  personal information.") }}
You've got two spaces before "personal information"

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +            {{ _("Schedule and send up to 50,000 messages to a list of recipients") }}
You can use `CSV_MAX_ROWS` in the config for this number.

Use a `{}` in your string and the helper `format_number` to deal with thousands separator in French/English

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +        <!-- -->
Remove?

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
>          <!-- -->
Remove?

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +            {{ _("GC Notify is managed by the Canadian Digital Service  with no costs for departments that use the service.") }}
two spaces before "with no costs"

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +              {{ _("Send up to 10 million emails per year and up to 25,000 text messages per year, completely free.")}}
Should be able to use the config `DEFAULT_FREE_SMS_FRAGMENT_LIMITS` with `central`. I think it's already used somewhere in the codebase, you can do a quick search

2021-01-27 15:52 UTC, AntoineAugusti commented on app/templates/views/signedout.html
> +  <!-- end section 7 -->
?

2021-01-27 15:54 UTC, RenDavidDimen commented on app/templates/views/signedout.html
> +              {{ _("Personalise your messages, while protecting  personal information.") }}
Good catch! 🕵️‍♂️

2021-01-27 16:02 UTC, RenDavidDimen commented on app/templates/views/signedout.html
> +  <div class="bg-blue" role="main">
Can confirm that it is no longer being used 👍

2021-01-27 16:34 UTC, anikbrazeau requested changes
This is great! Thanks for making it happen! 👍 

Three small things:

- Change link destination for "How GC Notify meets government needs" / "Comment GC Notification répond aux besoins du gouvernement" to go to "Why GC Notify" page
- Change FR equivalent of "Skip the procurement process" to "Nul besoin d'approvisionnement"
- Can we upload a new first image for the personalised template to match Figma (new illustration shows transactional example and not text message specific)

2021-01-27 20:25 UTC, RenDavidDimen commented on app/translations/csv/fr.csv
> +"What you can do with GC Notify","Avec GC Notification, vous pouvez :"
Found another string with a different translation. Currently talking with design to see if we can find a solution to this

2021-01-27 20:30 UTC, AntoineAugusti commented on app/main/views/index.py
> +        default_free_sms_fragment_limits_central=current_app.config.get('DEFAULT_FREE_SMS_FRAGMENT_LIMITS', {}).get('central', 10000),
```suggestion
        default_free_sms_fragment_limits_central=current_app.config['DEFAULT_FREE_SMS_FRAGMENT_LIMITS']['central'],
```
Don't want to fallback to another value if this config dict gets updated, we would need to change code here and this is expected

2021-01-28 21:20 UTC, AntoineAugusti approved these changes
LGTM 🚢  Good work 🥳 

Before merging, add cache headers in staging, upload files in prod, set cache headers as discussed on Slack.

2021-01-29 15:01 UTC, anikbrazeau approved these changes
Looks great! Thanks for your patience on this one!

2021-01-29 15:03 UTC, merged