Review and contextualize API integration section
cds-snc/notification-admin pull request #912
Opened 2021-02-17 03:01 UTC by anikbrazeau

# Summary | Résumé

- add links to documentation
- add structure to pages
- add context to explain concepts

2021-02-17 03:05 UTC, anikbrazeau commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make clear connections from GC Notify interface to documentation site by adding contextualization and links](https://trello.com/c/ZVIwr1Wa/270-make-clear-connections-from-gc-notify-interface-to-documentation-site-by-adding-contextualization-and-links)

2021-02-17 13:39 UTC, AntoineAugusti requested changes

2021-02-17 13:39 UTC, AntoineAugusti commented on app/translations/csv/fr.csv
> +"Add an endpoint where GC Notify should send POST requests","Ajouter un point de terminaison où la GC Notification peut envoyer les demandes ‘POST’"
```suggestion
"Add an endpoint where GC Notify should send POST requests","Ajouter un point de terminaison où GC Notification peut envoyer les requêtes ‘POST’"
```
On utilise "requête HTTP" en français

2021-02-17 13:39 UTC, AntoineAugusti commented on app/templates/views/api/callbacks/delivery-status-callback.html
> +        {{ _('When you send an email or text message, find out if GC Notify was able to deliver it with callbacks. Learn more in the ') }} <a href="{{ documentation_url('callbacks') }}">{{ _('callbac
Should be a single sentence and inject the documentation URL in it. Look for other templates/translation strings with a `<a href='{}'` in it

2021-02-17 13:39 UTC, AntoineAugusti commented on app/templates/views/api/keys.html
> +    {{ _('Learn more in the ') }} <a href="{{ documentation_url('keys') }}">{{ _('API key documentation') }}</a>.
Should be a single sentence and inject the documentation URL in it. Look for other templates/translation strings with a `<a href='{}'` in it

2021-02-17 13:39 UTC, AntoineAugusti commented on app/templates/views/api/keys/create.html
> +    {{ _('Learn about types of API keys and when to use them in the ') }} <a href="{{ documentation_url('keys') }}">{{ _('API key documentation') }}</a>.
Should be a single sentence and inject the documentation URL in it. Look for other templates/translation strings with a `<a href='{}'` in it

2021-02-17 13:39 UTC, AntoineAugusti commented on app/templates/views/api/safelist.html
> +    {{ _('to limit sending to a few specific people.') }}
Should be a single sentence and inject the documentation URL in it. Look for other templates/translation strings with a `<a href='{}'` in it

2021-02-17 13:39 UTC, AntoineAugusti commented on app/templates/views/api/safelist.html
> +        {{ _('You can test emails with these addresses.') }}
I'm a bit confused by the wording. I think it can be understood in another way, like "if I send stuff to these values, notifications will not be sent but I'll get a dummy response to test out my integration".

Or is it just me?

2021-03-04 13:20 UTC, anikbrazeau commented on app/templates/views/api/safelist.html
> +        {{ _('You can test emails with these addresses.') }}
Oh you're right, it's a bit confusing, we can remove this text altogether.

2021-03-04 13:47 UTC, AntoineAugusti approved these changes

2021-03-04 13:59 UTC, merged