Mobile menu transformed into an overlay menu
cds-snc/notification-admin pull request #944
Opened 2021-03-11 23:52 UTC by jimleroyer

# Summary | Résumé

[The mobile menu should overlay the page](https://trello.com/c/KnePeyHr/331-nav-bug-the-mobile-main-menu-should-push-down-the-page).

Per the design, the mobile menu should push down the content. After some testing and discussion, we decided to use an overlay like the mobile account menu.

# Test instructions | Instructions pour tester la modification

1. Get to the Notify website under a mobile viewport.
2. Click on the menu button.

1. Get to the Notify website under a mobile viewport.
2. Login.
3. Click on the menu button.

You should see that the previous menus are kept and exactly the same, except for the fact they now appear in a modal overlay menu.

# UI Animation Demo

![menu-mobile-overlay-01](https://user-images.githubusercontent.com/805567/110870665-eac0a400-829a-11eb-8d06-64342e8e2207.gif)

# Help requested | Aide requise

## Style of the selected page

For now, I have defined the selected page to be bold and underline:

![image](https://user-images.githubusercontent.com/805567/110870418-65d58a80-829a-11eb-9a63-bc068928dd3d.png)

## The menu icon

The menu icon is still the same as the account icon. Is that okay for now or we have something else to use? 

![image](https://user-images.githubusercontent.com/805567/110870477-87cf0d00-829a-11eb-9c61-69c9c69cb95b.png)

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

2021-03-11 23:53 UTC, jimleroyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [NAV Bug: The mobile main menu should overlay the page](https://trello.com/c/KnePeyHr/331-nav-bug-the-mobile-main-menu-should-push-down-the-page)

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/components/nav_menu_item_mobile.html
> +          alt="Open link in new window"
Can this be translated?

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +    <div class="modal-content text-left h-auto p-0 mt-8 mb-4 mx-0">
The documentation link colour is different
![Screen Shot 2021-03-12 at 14 10 55](https://user-images.githubusercontent.com/295709/110987341-eea50280-833c-11eb-984d-3f6e0a8aed92.png)

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/components/nav_menu_item_mobile.html
> +                              is_selected=False, is_external_link=False, css_classes=None) %}
Indentation seems off. Do other macros use the same indentation style?

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +            alt="Close button"
Can this be translated?

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +          {{ nav_menu_item_mobile(documentation_url(), _('Documentation'), False, True) }}
Maybe use keyword args to say that `True` refers to external?

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +      </div>
The account icon is displayed when you're logged out. Is it on purpose? Should it be hidden or go to sign in/register?

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav.html
>              {{ _('Menu') }}
The down arrow icon gives the impression that the menu will open "below" but it appears full screen, the experience is a bit weird

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +          {{ nav_menu_item_mobile('/',_('Home'),header_navigation.is_selected('home')) }}
The "home" link is sometimes highlighted (with the yellow/orange background) when I'm on another page. Go to contact us > open the menu > "Home" is highlighted

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/components/nav_menu_item_mobile.html
> +                              is_selected=False, is_external_link=False, css_classes=None) %}
Wondering if the component can use the passed `url` and compare it to the current URL to determine the `is_selected` value. It's a bit of a burden to pass it every time.

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/components/nav_menu_item_mobile.html
> +                              is_selected=False, is_external_link=False, css_classes=None) %}
I think we've got a utils/a method available on the sign-in/2FA views to determine if a link is external, you may not need the `is_external_link` attribute

2021-03-12 19:24 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +<div
Is this file duplicated with another one? The list of links in particular. Can links be put in a partial and included in both templates?

2021-03-12 19:27 UTC, e-pang requested changes
This looks and feel so much better already!
A few small updates if possible.

- Remove the account icon and replace with the word “Menu” font size 25px
- Bold as the current page works well, thanks!
- Remove underlined of current page
- Can we add the underline as the hover? (not needed on mobile, but good if the user just has they view port smaller on desktop)
- I think I see two different colours for the links (visited and not visited). The links in the menu can always stay as #26374A 

Other than that I think it looks great and works really well, thank you!

2021-03-12 20:42 UTC, e-pang commented
Wanted to note that we should also bring these updates to the mobile account menu. Should I open a card on trello for this? 
- Bold as the current page
- Remove underlined of current page
- Add the underline as the hover
- The links in the menu can always stay as #26374A regardless of visited or not visited

2021-03-15 14:55 UTC, jimleroyer reviewed
Many of my replies are in Pending mode and it looks like I haven't replied to comments. I am testing github approval process to see if that will somehow unblock my ability to comment.

2021-03-15 14:55 UTC, jimleroyer commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +<div
It is not a duplicate. Although, some logic between mobile and desktop could be shared. It would be nice to have some sort of resolver for links based on contextual navigation, but it won't be feasible without considerable effort. I would let @dorianjp chime in on this topic because he has more knowledge.

2021-03-15 15:05 UTC, jimleroyer commented on app/templates/components/nav_menu_item_mobile.html
> +                              is_selected=False, is_external_link=False, css_classes=None) %}
It could be, but not sure that would be the most reliable way to determine it. I would push this for another time if we want to consider this with some more talk.

2021-03-15 15:36 UTC, AntoineAugusti approved these changes

2021-03-15 15:36 UTC, AntoineAugusti commented on app/templates/components/nav_menu_item_mobile.html
> +          alt="Open link in new window"
Sounds good!

2021-03-15 15:36 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +            alt="Close button"
Sounds good

2021-03-15 15:36 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +          {{ nav_menu_item_mobile('/',_('Home'),header_navigation.is_selected('home')) }}
I think it was fixed in https://github.com/cds-snc/notification-admin/pull/942

2021-03-15 15:36 UTC, AntoineAugusti commented on app/templates/partials/nav/gc_header_nav_mobile.html
> +<div
Nice, would you be able to write a refactor Trello card?

2021-03-15 15:59 UTC, e-pang approved these changes
These are looking great, thanks for making the requested updates Jimmy!

2021-03-15 16:06 UTC, e-pang commented on app/templates/partials/nav/gc_header_nav.html
>              {{ _('Menu') }}
I recommend removing the arrow for now (and decreasing the width of the button). I agree it set the wrong expectations. Thanks for the flag!

2021-03-15 18:24 UTC, e-pang approved these changes
Looks go to me, thanks for the update!

2021-03-15 18:35 UTC, e-pang reviewed
Focus states work great on Chrome/Edge. I tried it out on Firefox and it has big some issues. The focus state goes from the close button to the browser chrome and never gets to the menu items. Not sure if we're worried about Firefox, but thought. I would mention it.

2021-03-15 20:30 UTC, jimleroyer commented
We tested a bit more Firefox and we realized we need to enable a preference called `accessibility.tabfocus` in order for TAB navigation to work. It's all good in the end.

2021-03-15 20:30 UTC, merged