Better error messaging when blocked by Trial
cds-snc/notification-admin pull request #965
Opened 2021-03-23 20:25 UTC by jimleroyer

# Summary | Résumé

[TRELLO](https://trello.com/c/U7h3nIX5/371-level-1-update-trial-to-live-messaging-notify-wide): Improves the error messages upon sending a message.

# Test instructions | Instructions pour tester la modification

Manual tests: 

1. Get around the screens to send messages.
2. Verify the messages are correctly changed. 

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

2021-03-23 20:28 UTC, jimleroyer commented on app/templates/partials/check/too-many-messages.html
>    .
Notice the `.` sitting after the condition to catch both message variations.

2021-03-23 20:59 UTC, AntoineAugusti commented on app/templates/partials/check/not-allowed-to-send-to.html
> +  {{ _('In trial mode, you can only send to yourself and members of your team. To send to more recipients, request to go live.') }}
Did we consider making this part a link?

2021-03-23 20:59 UTC, AntoineAugusti commented on app/templates/partials/check/too-many-messages.html
> +    {{ _('in trial mode. To send more messages, request to go live') }}
Did we consider making this part a link?

2021-03-23 21:12 UTC, jimleroyer commented on app/templates/partials/check/not-allowed-to-send-to.html
> +  {{ _('In trial mode, you can only send to yourself and members of your team. To send to more recipients, request to go live.') }}
That would be a nice improvement. We'd need to plug-in proper permissions check though as not everyone can go to that page. Let me ask @anikbrazeau

2021-03-23 21:12 UTC, jimleroyer commented on app/templates/partials/check/too-many-messages.html
> +    {{ _('in trial mode. To send more messages, request to go live') }}
That would be a nice improvement. We'd need to plug-in proper permissions check though as not everyone can go to that page. Let me ask @anikbrazeau

2021-03-24 13:02 UTC, anikbrazeau commented on app/templates/partials/check/not-allowed-to-send-to.html
> +  {{ _('In trial mode, you can only send to yourself and members of your team. To send to more recipients, request to go live.') }}
Yes! That is the intention, sorry if it wasn't clear, maybe the comments got hidden in [Google Docs](https://docs.google.com/document/d/1rnNDriR53NgVzY4TjBPnKfMpK_2exg_16JwGG0rYBZQ/edit)?

Link: "members of your team" and "membres de votre équipe" to the team page
Link "request to go live" and "activez votre service" to the request to go live page

2021-03-24 13:04 UTC, anikbrazeau commented on app/templates/partials/check/not-allowed-to-send-to.html
> +  {{ _('In trial mode, you can only send to yourself and members of your team. To send to more recipients, request to go live.') }}
If the user does not have permission to manage settings and therefore no access to request to go live, consider linking to a page like https://www.figma.com/file/A4yAAkCGUaqoaTjpWL411i/Going-from-TRIAL-to-LIVE-Activation-du-service?node-id=1236%3A4652 like for the tooltip?

2021-03-24 13:04 UTC, anikbrazeau commented on app/templates/partials/check/too-many-messages.html
> +    {{ _('in trial mode. To send more messages, request to go live') }}
Yes, same comments as above, please link :)

2021-03-25 20:01 UTC, anikbrazeau commented
Can we add a link for "team members" and "membres de votre équipe" to the team page, if they're not quite ready to go live yet and want to invite people instead?

2021-03-25 20:14 UTC, jimleroyer commented
@anikbrazeau We'd need to discuss more offline about this, I am not sure what is the ask. This does not seem to be scoped by the current task and better error message, is it? can we update the Trello card if that is the case?

2021-03-26 18:15 UTC, jimleroyer commented on tests/app/main/views/test_service_settings.py
> +    ]}
I had to reuse the `active_user_no_settings_permission` fixture as other similar ones with correct permissions did not work out of the box. It seems a lot of test fixtures we load in tests such as `client_request` are strongly coupled with `active_user_no_settings_permission` and using another on might lead to test failures. So I ended up overriding permissions for this fixture to get it to work (instead of using another "more appropriate" one).

2021-03-26 18:16 UTC, jimleroyer commented on app/main/views/service_settings.py
> +        return render_template('views/service-settings/request-to-go-live.html')
@AntoineAugusti I increased the allowed permissions for this endpoint and provide different template rendering based on different permissions. This allow us to reuse the same endpoint but providing a different view based on the user. Tell me if you are OK with this approach.

2021-03-26 18:19 UTC, jimleroyer commented
I talked to @anikbrazeau offline, she clarified for me what the link for "team members" and "membres de votre équipe". After our talk, I added the mentioned link. It is present on the deployed Heroku at the moment. 

This PR is ready to be reviewed again, addressing all raised PR comments.

2021-03-29 11:42 UTC, AntoineAugusti requested changes
Good work, still a few minor things and then it'll be perfect

2021-03-29 11:42 UTC, AntoineAugusti commented on app/main/views/service_settings.py
> +        return render_template('views/service-settings/request-to-go-live.html')
Sounds good. I think there are tests related to permissions in the associated test file, could you add a test here? `test_route_permissions`

2021-03-29 11:42 UTC, AntoineAugusti commented on app/templates/partials/check/too-many-messages.html
> +    {{ _('in trial mode. To send more messages, request to go live') }}
@jimleroyer You're missing a link to request to go live here

2021-03-29 11:42 UTC, AntoineAugusti commented on app/templates/partials/check/too-many-messages.html
>    {{ _('You can only send') }} {{ current_service.message_limit }} {{ _('messages per day') }}
I know it's not your code but could you format this number here? `| format_number` I think

2021-03-30 11:34 UTC, AntoineAugusti approved these changes

2021-03-30 14:07 UTC, merged