Trial welcome screen
cds-snc/notification-admin pull request #967
Opened 2021-03-24 13:52 UTC by RenDavidDimen

# Summary | Résumé

Adding welcome screen for new users to Notify that gives context of being in Trial mode and directs them to creating their first service.
---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

Added additional test file for the welcome page and updated the previous flow logic to go from `Verify>Add Service` to 
 `Verify>Welcome>Add Service`

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

2021-03-24 14:30 UTC, AntoineAugusti requested changes

2021-03-24 14:30 UTC, AntoineAugusti commented on app/templates/views/welcome.html
> +            <li class="pt-4 text-base leading-tight">{{ _('Send up to 50 messages per day') }}</li>
Can use this config variable to avoid hardcoding 50 https://github.com/cds-snc/notification-admin/blob/ab66b7d7b4e2edf134d308fcc8718439093897c2/app/config.py#L57

+ use `format_number`

2021-03-24 14:30 UTC, AntoineAugusti commented on app/translations/csv/fr.csv
> +"In <b>trial mode</b>, you can:","En mode d’essai, vous pourrez:"
Trial mode is not in bold in French

2021-03-24 14:30 UTC, AntoineAugusti commented on app/translations/csv/fr.csv
> +"Send up to 50 messages per day","Envoyer jusqu'à 50 messages par jour"
Don't hardcode the number in the translation

2021-03-24 14:30 UTC, AntoineAugusti commented on app/templates/views/welcome.html
> +    <div class="pb-16">
For all classes, is `text-base` needed? It's not the default?

2021-03-24 14:30 UTC, AntoineAugusti commented on app/templates/views/welcome.html
> +        <p class="pt-4 text-base">{{ _('To get started, you’ll need to create a service. A service is a shared space where you and your team can write messages and track sending. Your service will st
@anikbrazeau We explain what a trial is, that's great! Wondering if we want to highlight the next step, and tell them that they can lift restrictions after they tested the product by requesting to go live. Is it the right place? Coming later in the product?

2021-03-24 14:30 UTC, AntoineAugusti commented on tests/app/main/views/test_welcome.py
> +            'email': api_user_active['email_address']}
Don't think you need to set up an active user because this page is visible if you're not logged in.

Could reuse https://github.com/cds-snc/notification-admin/blob/ab66b7d7b4e2edf134d308fcc8718439093897c2/tests/app/main/views/test_index.py#L111-L117, I think there is a property to pass to check the page title at the same time

2021-03-24 14:30 UTC, AntoineAugusti commented on app/templates/views/welcome.html
> +        <a href="{{ url_for('main.add_service', first='first') }}" class="mt-16 button button-blue hover:bg-blue-selected">{{ _('Create your first service') }}</a>
Do we want to change the hover style just for this button or wait to do a complete sweep of buttons and change the hover style there?

2021-03-24 14:30 UTC, AntoineAugusti commented on app/translations/csv/fr.csv
> +"Welcome to GC Notify","Bienvenue à GC Notification"
Is it the right French translation? "Bienvenue à" seems weird to me

2021-03-24 14:30 UTC, AntoineAugusti commented on app/main/views/index.py
> +    )
```suggestion
    return render_template('views/welcome.html')
```
💅

2021-03-24 14:30 UTC, AntoineAugusti commented on app/assets/javascripts/main.min.js
> -(()=>{var e={1924:(e,t,n)=>{"use strict";var a=n(210),s=n(5559),r=s(a("String.prototype.indexOf"));e.exports=function(e,t){var n=a(e,!!t);return"function"==typeof n&&r(e,".prototype.")>-1?s(n):n}},55
Wondering why this diff is so large.

2021-03-24 15:01 UTC, RenDavidDimen commented on app/translations/csv/fr.csv
> +"Welcome to GC Notify","Bienvenue à GC Notification"
"Bienvenue à" seems to be what is currently in the Figma file, perhaps @anikbrazeau can verify this is fine?

2021-03-24 15:15 UTC, RenDavidDimen commented on app/templates/views/welcome.html
> +    <div class="pb-16">
When looking at the other code, I had believed that this was for accessibility reasons, however it seems that the the content will inherit the rem font-size value from a parent and is not necessarily required. Will remove 👍

2021-03-24 15:27 UTC, RenDavidDimen commented on app/assets/javascripts/main.min.js
> -(()=>{var e={1924:(e,t,n)=>{"use strict";var a=n(210),s=n(5559),r=s(a("String.prototype.indexOf"));e.exports=function(e,t){var n=a(e,!!t);return"function"==typeof n&&r(e,".prototype.")>-1?s(n):n}},55
Not quite sure myself, I'm curious about the recent `npm install` I had ran since it updated the package.json.lock and `npm run tailwind` seems to have added a pair of LICENSE.txt files (one of them being the `main.min.js.LICENSE.txt` file).

2021-03-24 16:03 UTC, anikbrazeau commented on app/translations/csv/fr.csv
> +"Welcome to GC Notify","Bienvenue à GC Notification"
Let's go with "Bienvenue dans GC Notification" instead. Thanks for flagging.

2021-03-24 16:06 UTC, anikbrazeau commented on app/templates/views/welcome.html
> +        <a href="{{ url_for('main.add_service', first='first') }}" class="mt-16 button button-blue hover:bg-blue-selected">{{ _('Create your first service') }}</a>
Let’s go with the same as the “Create an account” button for now and reevaluate all button hovers in another focused task?

2021-03-24 16:36 UTC, anikbrazeau commented on app/templates/views/welcome.html
> +        <a href="{{ url_for('main.add_service', first='first') }}" class="mt-16 button button-blue hover:bg-blue-selected">{{ _('Create your first service') }}</a>
Let's stick with the same as https://notification.canada.ca/register for now for consistency.
We'll need to do a sweep of buttons soon across the platform, but that can be a subsequent task.

2021-03-24 16:42 UTC, anikbrazeau commented on app/templates/views/welcome.html
> +        <p class="pt-4 text-base">{{ _('To get started, you’ll need to create a service. A service is a shared space where you and your team can write messages and track sending. Your service will st
Good point.. we were thinking later at first might be better, but since we've scoped it to error messages only for now. 

Let's add a new line here in the interim. 

Just before the button, something like:

`Once you've set up your team and tried out sending, you can request to go live in settings`

`Une fois que vous aurez mis en place votre équipe et essayé d'envoyer des messages, vous pourrez demander d'activer votre service dans les paramètres`

2021-03-24 19:39 UTC, anikbrazeau commented
If folks abandon the onboarding or close Notify before creating a service, will they also get the Welcome page when they sign in again?

Right now, I think they get this page: 
![Screen Shot 2021-03-24 at 12 31 15 PM](https://user-images.githubusercontent.com/38330843/112373237-1ab67100-8cb7-11eb-9729-98e76579fb22.png)

2021-03-25 17:39 UTC, RenDavidDimen commented on app/assets/javascripts/main.min.js
> -(()=>{var e={1924:(e,t,n)=>{"use strict";var a=n(210),s=n(5559),r=s(a("String.prototype.indexOf"));e.exports=function(e,t){var n=a(e,!!t);return"function"==typeof n&&r(e,".prototype.")>-1?s(n):n}},55
It looks like merging in changes from master has added these changes. I believe no changes to `main.min.js` occur in this PR now

2021-03-25 18:11 UTC, anikbrazeau approved these changes
This looks great in heroku! Thanks for quick turnaround on changes!

2021-03-25 18:12 UTC, AntoineAugusti requested changes
A few small things. Can you remove unrelated changes to licenses + `package-lock.json`

2021-03-25 18:12 UTC, AntoineAugusti commented on app/assets/stylesheets/tailwind/components/typography.css
> +    font-weight: bolder;
It was not defined before? Why not `bold`?

2021-03-25 18:12 UTC, AntoineAugusti commented on tests/app/main/views/test_welcome.py
> +from bs4 import BeautifulSoup
Can you move that to `test_index.py`? Don't think this view deserves its own file

2021-03-25 18:49 UTC, RenDavidDimen commented on app/assets/stylesheets/tailwind/components/typography.css
> +    font-weight: bolder;
This was being overwritten before to `font-weight:normal` in the `reset.css` file to flatten all browser defaults and styles inherited from gov.uk template. I believe it was for that reason that the `<b>` tags were not being bolded on the page.

That being said, `bold` fits better here. I'll update that 👍

2021-03-25 19:34 UTC, AntoineAugusti approved these changes
LGTM.

Remove the `package-lock.json` changes and then :shipit:

2021-03-25 21:01 UTC, merged