Feat/automatic accessibility
cds-snc/notification-admin pull request #994
Opened 2021-04-16 21:19 UTC by jimleroyer

# Summary | Résumé

Added automated a11y test for the authenticated service dashboard page.

# Test instructions | Instructions pour tester la modification

Run the test suite! 🏃 

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux
      langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce
      que ça devrait être divisé en de plus petites demandes de tirage (« pull
      requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2021-04-16 21:27 UTC, maxneuvians commented
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/078d2045d24aa157cd2ce82397312ed3a456f9b1

2021-04-19 13:59 UTC, AntoineAugusti requested changes

2021-04-19 13:59 UTC, AntoineAugusti commented on tests/app/main/views/test_dashboard.py
> +    a11y_test(url, response.data.decode('utf-8'))
Could you pass the full URL? We have a base and this page is without a base, see https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/078d2045d24aa157cd2ce82397312ed3a456f9b1

You can tweak the function to ensure a full URL is passed or preprend the admin base if you want.

2021-04-19 13:59 UTC, AntoineAugusti commented on tests/app/main/views/test_dashboard.py
> +def test_dashboard_page_a11y(
Could you call `a11y_test` in an existing test and not create a test case just to pass a HTML payload to the a11y tester? I believe other tests in this file already do similar things.

2021-04-19 18:26 UTC, jimleroyer commented on tests/app/main/views/test_dashboard.py
> +def test_dashboard_page_a11y(
It could be a matter of style: I personally prefer to have one focused test per concern for a variety of reasons. It makes it clear we are testing the a11y output so no future maintainer will delete, or mark @ignored a changes containing this, or just modifying it in a way where the a11y is affected. It is a rule of thumb for me, there are cases I could deviate from this. 

What do you think? What do you consider the limit (in lines of code, or tested concerns) of what a unit-test should contain?

2021-04-19 19:25 UTC, AntoineAugusti commented on tests/app/main/views/test_dashboard.py
> +def test_dashboard_page_a11y(
Agreed that's something we can debate. Our current test usually contain various assertions including mocks, asserting database states, inspecting the page's content etc. I think that it's best to keep continue doing as is. Our tests suite could go or become slow if we duplicate various scenarios to test for various things like page content, database, mock calls, a11y.

You could add a [pytest custom marker](https://docs.pytest.org/en/stable/example/markers.html) though! `@pytest.mark.a11y` Be sure to look at how to register those.

2021-04-19 22:14 UTC, jimleroyer commented on tests/app/main/views/test_dashboard.py
> +    a11y_test(url, response.data.decode('utf-8'))
I've made use of the [`_external` parameter of the `url_for` method](https://flask.palletsprojects.com/en/1.1.x/api/#flask.url_for) to get the full URL.

2021-04-19 22:16 UTC, maxneuvians commented
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/7c43600c592a4e1fc3a96f26a325514af50464a9

2021-04-19 22:21 UTC, jimleroyer commented on tests/app/main/views/test_dashboard.py
> +def test_dashboard_page_a11y(
The `@pytest.mark.a11y` is definitely a good compromise.

To expand a bit on the topic, I understand that longer tests might be acceptable when heavy performance resources are involved, especially for integration tests, as unit-tests should not be heavy and very quick to execute. The tests for accessibility in general can benefit from mocked calls that do not involve external calls to database and network bur rather be CPU intensive and hence, quick to execute.

To my personal taste, I can see that some existing tests are quite long sometimes and harder to understand. It's possible it is hard to avoid. It's something that nodejs test libraries can do better IMO because of nested tests within nested resources loading closures, but not easy using pytest here.

We can chat offline tomorrow morning if you want. Ultimately, I offer my perspective but I'll let you decide on the style you want to see in the project.

2021-04-20 14:22 UTC, AntoineAugusti approved these changes
LGTM :shipit:

2021-04-20 14:30 UTC, maxneuvians commented
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/fe6a24456c0b0494c5393ffa1a19ad5fe685fb37

2021-04-20 15:57 UTC, merged

2021-04-20 16:03 UTC, maxneuvians commented
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/25710ef09d2cf0de5a9904c7ce76acb8657dcf4e